name = "JMLIRCore"
uuid = "94029c64-618c-4c5d-afcf-c534916f7e83"
version = "1.0.0-DEV"
authors = ["Benedict Short <benedictnjshort@gmail.com> and contributors"]

[deps]
LLVM = "929cbde3-209d-540e-8aea-75f648917ca0"
MLIR = "bfde9dd4-8f40-4a1e-be09-1475335e1c92"

[compat]
LLVM = "9.1.3"
MLIR = "0.1.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
