// Generated by CIRCT unknown git version
module arith_index_cast_in_ui1_out_ui64(
  input         in0,
                in0_valid,
                out0_ready,
  output        in0_ready,
  output [63:0] out0,
  output        out0_valid
);

  assign in0_ready = out0_ready & in0_valid;
  assign out0 = {64{in0}};
  assign out0_valid = in0_valid;
endmodule

