// Generated by CIRCT unknown git version
module arith_addi_in_ui64_ui64_out_ui64(	// -:19:22
  input  [63:0] in0,
  input         in0_valid,
  input  [63:0] in1,
  input         in1_valid,
                out0_ready,
  output        in0_ready,
                in1_ready,
  output [63:0] out0,
  output        out0_valid
);

  wire _GEN = in0_valid & in1_valid;	// -:19:22
  wire _GEN_0 = out0_ready & _GEN;	// -:19:22
  assign in0_ready = _GEN_0;	// -:19:22
  assign in1_ready = _GEN_0;	// -:19:22
  assign out0 = in0 + in1;	// -:19:22
  assign out0_valid = _GEN;	// -:19:22
endmodule

