// Generated by CIRCT unknown git version
module arith_cmpi_in_ui64_ui64_out_ui1_slt(	// -:40:10
  input  [63:0] in0,
  input         in0_valid,
  input  [63:0] in1,
  input         in1_valid,
                out0_ready,
  output        in0_ready,
                in1_ready,
                out0,
                out0_valid
);

  wire _GEN = in0_valid & in1_valid;	// -:40:10
  wire _GEN_0 = out0_ready & _GEN;	// -:40:10
  assign in0_ready = _GEN_0;	// -:40:10
  assign in1_ready = _GEN_0;	// -:40:10
  assign out0 = $signed(in0) < $signed(in1);	// -:40:10
  assign out0_valid = _GEN;	// -:40:10
endmodule

