// Generated by CIRCT unknown git version
module arith_xori_in_ui1_ui1_out_ui1(	// -:57:11
  input  in0,
         in0_valid,
         in1,
         in1_valid,
         out0_ready,
  output in0_ready,
         in1_ready,
         out0,
         out0_valid
);

  wire _GEN = in0_valid & in1_valid;	// -:57:11
  wire _GEN_0 = out0_ready & _GEN;	// -:57:11
  assign in0_ready = _GEN_0;	// -:57:11
  assign in1_ready = _GEN_0;	// -:57:11
  assign out0 = in0 ^ in1;	// -:57:11
  assign out0_valid = _GEN;	// -:57:11
endmodule

