// Generated by CIRCT unknown git version
module arith_index_cast_in_ui64_out_ui64(	// -:82:11
  input  [63:0] in0,
  input         in0_valid,
                out0_ready,
  output        in0_ready,
  output [63:0] out0,
  output        out0_valid
);

  assign in0_ready = out0_ready & in0_valid;	// -:82:11
  assign out0 = in0;	// -:82:11
  assign out0_valid = in0_valid;	// -:82:11
endmodule

