// Generated by CIRCT unknown git version
module arith_select_in_ui1_ui64_ui64_out_ui64(	// -:75:11
  input         in0,
                in0_valid,
  input  [63:0] in1,
  input         in1_valid,
  input  [63:0] in2,
  input         in2_valid,
                out0_ready,
  output        in0_ready,
                in1_ready,
                in2_ready,
  output [63:0] out0,
  output        out0_valid
);

  wire _GEN = in0_valid & in1_valid & in2_valid;	// -:75:11
  wire _GEN_0 = out0_ready & _GEN;	// -:75:11
  assign in0_ready = _GEN_0;	// -:75:11
  assign in1_ready = _GEN_0;	// -:75:11
  assign in2_ready = _GEN_0;	// -:75:11
  assign out0 = in0 ? in1 : in2;	// -:75:11
  assign out0_valid = _GEN;	// -:75:11
endmodule

