// Generated by CIRCT unknown git version
module handshake_constant_c262144_out_ui64(	// -:15:20
  // input  /*Zero Width*/ ctrl,
     input                 ctrl_valid,
                           out0_ready,
     output                ctrl_ready,
     output [63:0]         out0,
     output                out0_valid
);

  assign ctrl_ready = out0_ready;	// -:15:20
  assign out0 = 64'h40000;	// -:15:20
  assign out0_valid = ctrl_valid;	// -:15:20
endmodule

