// Generated by CIRCT unknown git version
module handshake_constant_c843314857_out_ui64(	// -:3:23
  // input  /*Zero Width*/ ctrl,
     input                 ctrl_valid,
                           out0_ready,
     output                ctrl_ready,
     output [63:0]         out0,
     output                out0_valid
);

  assign ctrl_ready = out0_ready;	// -:3:23
  assign out0 = 64'h3243F6A9;	// -:3:23
  assign out0_valid = ctrl_valid;	// -:3:23
endmodule

