// Generated by CIRCT unknown git version
module handshake_mux_in_ui1_3ins_1outs_ctrl(
     input                 select,
                           select_valid,
  // input  /*Zero Width*/ in0,
     input                 in0_valid,
  // input  /*Zero Width*/ in1,
     input                 in1_valid,
                           out0_ready,
     output                select_ready,
                           in0_ready,
                           in1_ready,
  // output /*Zero Width*/ out0,
     output                out0_valid
);

  wire [1:0] _GEN = 2'h1 << select;
  wire       _GEN_0 = (select ? in1_valid : in0_valid) & select_valid;
  wire       _GEN_1 = _GEN_0 & out0_ready;
  assign select_ready = _GEN_1;
  assign in0_ready = _GEN[0] & _GEN_1;
  assign in1_ready = _GEN[1] & _GEN_1;
  // Zero width: assign out0 = /*Zero width*/;
  assign out0_valid = _GEN_0;
endmodule

