// Generated by CIRCT unknown git version
module handshake_buffer_in_ui1_out_ui1_1slots_seq_init_0(
  input  in0,
         in0_valid,
         clock,
         reset,
         out0_ready,
  output in0_ready,
         out0,
         out0_valid
);

  reg  ready0_reg;
  reg  valid0_reg;
  wire _GEN = ~valid0_reg | ~ready0_reg;
  reg  data0_reg;
  reg  ctrl_data0_reg;
  always_ff @(posedge clock) begin
    if (reset) begin
      valid0_reg <= 1'h1;
      data0_reg <= 1'h0;
      ready0_reg <= 1'h0;
      ctrl_data0_reg <= 1'h0;
    end
    else begin
      automatic logic _GEN_0 = ~out0_ready & ~ready0_reg;
      automatic logic _GEN_1 = out0_ready & ready0_reg;
      valid0_reg <= _GEN ? in0_valid : valid0_reg;
      data0_reg <= _GEN ? in0 : data0_reg;
      ready0_reg <= ~_GEN_1 & (_GEN_0 ? valid0_reg : ready0_reg);
      ctrl_data0_reg <= ~_GEN_1 & (_GEN_0 ? data0_reg : ctrl_data0_reg);
    end
  end // always_ff @(posedge)
  assign in0_ready = _GEN;
  assign out0 = ready0_reg ? ctrl_data0_reg : data0_reg;
  assign out0_valid = ready0_reg ? ready0_reg : valid0_reg;
endmodule

