// Generated by CIRCT unknown git version
module handshake_fork_1ins_86outs_ctrl(	// -:2:3
  // input  /*Zero Width*/ in0,
     input                 in0_valid,
                           clock,
                           reset,
                           out0_ready,
                           out1_ready,
                           out2_ready,
                           out3_ready,
                           out4_ready,
                           out5_ready,
                           out6_ready,
                           out7_ready,
                           out8_ready,
                           out9_ready,
                           out10_ready,
                           out11_ready,
                           out12_ready,
                           out13_ready,
                           out14_ready,
                           out15_ready,
                           out16_ready,
                           out17_ready,
                           out18_ready,
                           out19_ready,
                           out20_ready,
                           out21_ready,
                           out22_ready,
                           out23_ready,
                           out24_ready,
                           out25_ready,
                           out26_ready,
                           out27_ready,
                           out28_ready,
                           out29_ready,
                           out30_ready,
                           out31_ready,
                           out32_ready,
                           out33_ready,
                           out34_ready,
                           out35_ready,
                           out36_ready,
                           out37_ready,
                           out38_ready,
                           out39_ready,
                           out40_ready,
                           out41_ready,
                           out42_ready,
                           out43_ready,
                           out44_ready,
                           out45_ready,
                           out46_ready,
                           out47_ready,
                           out48_ready,
                           out49_ready,
                           out50_ready,
                           out51_ready,
                           out52_ready,
                           out53_ready,
                           out54_ready,
                           out55_ready,
                           out56_ready,
                           out57_ready,
                           out58_ready,
                           out59_ready,
                           out60_ready,
                           out61_ready,
                           out62_ready,
                           out63_ready,
                           out64_ready,
                           out65_ready,
                           out66_ready,
                           out67_ready,
                           out68_ready,
                           out69_ready,
                           out70_ready,
                           out71_ready,
                           out72_ready,
                           out73_ready,
                           out74_ready,
                           out75_ready,
                           out76_ready,
                           out77_ready,
                           out78_ready,
                           out79_ready,
                           out80_ready,
                           out81_ready,
                           out82_ready,
                           out83_ready,
                           out84_ready,
                           out85_ready,
     output                in0_ready,
  // output /*Zero Width*/ out0,
     output                out0_valid,
  // output /*Zero Width*/ out1,
     output                out1_valid,
  // output /*Zero Width*/ out2,
     output                out2_valid,
  // output /*Zero Width*/ out3,
     output                out3_valid,
  // output /*Zero Width*/ out4,
     output                out4_valid,
  // output /*Zero Width*/ out5,
     output                out5_valid,
  // output /*Zero Width*/ out6,
     output                out6_valid,
  // output /*Zero Width*/ out7,
     output                out7_valid,
  // output /*Zero Width*/ out8,
     output                out8_valid,
  // output /*Zero Width*/ out9,
     output                out9_valid,
  // output /*Zero Width*/ out10,
     output                out10_valid,
  // output /*Zero Width*/ out11,
     output                out11_valid,
  // output /*Zero Width*/ out12,
     output                out12_valid,
  // output /*Zero Width*/ out13,
     output                out13_valid,
  // output /*Zero Width*/ out14,
     output                out14_valid,
  // output /*Zero Width*/ out15,
     output                out15_valid,
  // output /*Zero Width*/ out16,
     output                out16_valid,
  // output /*Zero Width*/ out17,
     output                out17_valid,
  // output /*Zero Width*/ out18,
     output                out18_valid,
  // output /*Zero Width*/ out19,
     output                out19_valid,
  // output /*Zero Width*/ out20,
     output                out20_valid,
  // output /*Zero Width*/ out21,
     output                out21_valid,
  // output /*Zero Width*/ out22,
     output                out22_valid,
  // output /*Zero Width*/ out23,
     output                out23_valid,
  // output /*Zero Width*/ out24,
     output                out24_valid,
  // output /*Zero Width*/ out25,
     output                out25_valid,
  // output /*Zero Width*/ out26,
     output                out26_valid,
  // output /*Zero Width*/ out27,
     output                out27_valid,
  // output /*Zero Width*/ out28,
     output                out28_valid,
  // output /*Zero Width*/ out29,
     output                out29_valid,
  // output /*Zero Width*/ out30,
     output                out30_valid,
  // output /*Zero Width*/ out31,
     output                out31_valid,
  // output /*Zero Width*/ out32,
     output                out32_valid,
  // output /*Zero Width*/ out33,
     output                out33_valid,
  // output /*Zero Width*/ out34,
     output                out34_valid,
  // output /*Zero Width*/ out35,
     output                out35_valid,
  // output /*Zero Width*/ out36,
     output                out36_valid,
  // output /*Zero Width*/ out37,
     output                out37_valid,
  // output /*Zero Width*/ out38,
     output                out38_valid,
  // output /*Zero Width*/ out39,
     output                out39_valid,
  // output /*Zero Width*/ out40,
     output                out40_valid,
  // output /*Zero Width*/ out41,
     output                out41_valid,
  // output /*Zero Width*/ out42,
     output                out42_valid,
  // output /*Zero Width*/ out43,
     output                out43_valid,
  // output /*Zero Width*/ out44,
     output                out44_valid,
  // output /*Zero Width*/ out45,
     output                out45_valid,
  // output /*Zero Width*/ out46,
     output                out46_valid,
  // output /*Zero Width*/ out47,
     output                out47_valid,
  // output /*Zero Width*/ out48,
     output                out48_valid,
  // output /*Zero Width*/ out49,
     output                out49_valid,
  // output /*Zero Width*/ out50,
     output                out50_valid,
  // output /*Zero Width*/ out51,
     output                out51_valid,
  // output /*Zero Width*/ out52,
     output                out52_valid,
  // output /*Zero Width*/ out53,
     output                out53_valid,
  // output /*Zero Width*/ out54,
     output                out54_valid,
  // output /*Zero Width*/ out55,
     output                out55_valid,
  // output /*Zero Width*/ out56,
     output                out56_valid,
  // output /*Zero Width*/ out57,
     output                out57_valid,
  // output /*Zero Width*/ out58,
     output                out58_valid,
  // output /*Zero Width*/ out59,
     output                out59_valid,
  // output /*Zero Width*/ out60,
     output                out60_valid,
  // output /*Zero Width*/ out61,
     output                out61_valid,
  // output /*Zero Width*/ out62,
     output                out62_valid,
  // output /*Zero Width*/ out63,
     output                out63_valid,
  // output /*Zero Width*/ out64,
     output                out64_valid,
  // output /*Zero Width*/ out65,
     output                out65_valid,
  // output /*Zero Width*/ out66,
     output                out66_valid,
  // output /*Zero Width*/ out67,
     output                out67_valid,
  // output /*Zero Width*/ out68,
     output                out68_valid,
  // output /*Zero Width*/ out69,
     output                out69_valid,
  // output /*Zero Width*/ out70,
     output                out70_valid,
  // output /*Zero Width*/ out71,
     output                out71_valid,
  // output /*Zero Width*/ out72,
     output                out72_valid,
  // output /*Zero Width*/ out73,
     output                out73_valid,
  // output /*Zero Width*/ out74,
     output                out74_valid,
  // output /*Zero Width*/ out75,
     output                out75_valid,
  // output /*Zero Width*/ out76,
     output                out76_valid,
  // output /*Zero Width*/ out77,
     output                out77_valid,
  // output /*Zero Width*/ out78,
     output                out78_valid,
  // output /*Zero Width*/ out79,
     output                out79_valid,
  // output /*Zero Width*/ out80,
     output                out80_valid,
  // output /*Zero Width*/ out81,
     output                out81_valid,
  // output /*Zero Width*/ out82,
     output                out82_valid,
  // output /*Zero Width*/ out83,
     output                out83_valid,
  // output /*Zero Width*/ out84,
     output                out84_valid,
  // output /*Zero Width*/ out85,
     output                out85_valid
);

  wire allDone;	// -:2:3
  wire done85;	// -:2:3
  reg  emitted_0;	// -:2:3
  wire _GEN = ~emitted_0 & in0_valid;	// -:2:3
  wire done0 = out0_ready & _GEN | emitted_0;	// -:2:3
  reg  emitted_1;	// -:2:3
  wire _GEN_0 = ~emitted_1 & in0_valid;	// -:2:3
  wire done1 = out1_ready & _GEN_0 | emitted_1;	// -:2:3
  reg  emitted_2;	// -:2:3
  wire _GEN_1 = ~emitted_2 & in0_valid;	// -:2:3
  wire done2 = out2_ready & _GEN_1 | emitted_2;	// -:2:3
  reg  emitted_3;	// -:2:3
  wire _GEN_2 = ~emitted_3 & in0_valid;	// -:2:3
  wire done3 = out3_ready & _GEN_2 | emitted_3;	// -:2:3
  reg  emitted_4;	// -:2:3
  wire _GEN_3 = ~emitted_4 & in0_valid;	// -:2:3
  wire done4 = out4_ready & _GEN_3 | emitted_4;	// -:2:3
  reg  emitted_5;	// -:2:3
  wire _GEN_4 = ~emitted_5 & in0_valid;	// -:2:3
  wire done5 = out5_ready & _GEN_4 | emitted_5;	// -:2:3
  reg  emitted_6;	// -:2:3
  wire _GEN_5 = ~emitted_6 & in0_valid;	// -:2:3
  wire done6 = out6_ready & _GEN_5 | emitted_6;	// -:2:3
  reg  emitted_7;	// -:2:3
  wire _GEN_6 = ~emitted_7 & in0_valid;	// -:2:3
  wire done7 = out7_ready & _GEN_6 | emitted_7;	// -:2:3
  reg  emitted_8;	// -:2:3
  wire _GEN_7 = ~emitted_8 & in0_valid;	// -:2:3
  wire done8 = out8_ready & _GEN_7 | emitted_8;	// -:2:3
  reg  emitted_9;	// -:2:3
  wire _GEN_8 = ~emitted_9 & in0_valid;	// -:2:3
  wire done9 = out9_ready & _GEN_8 | emitted_9;	// -:2:3
  reg  emitted_10;	// -:2:3
  wire _GEN_9 = ~emitted_10 & in0_valid;	// -:2:3
  wire done10 = out10_ready & _GEN_9 | emitted_10;	// -:2:3
  reg  emitted_11;	// -:2:3
  wire _GEN_10 = ~emitted_11 & in0_valid;	// -:2:3
  wire done11 = out11_ready & _GEN_10 | emitted_11;	// -:2:3
  reg  emitted_12;	// -:2:3
  wire _GEN_11 = ~emitted_12 & in0_valid;	// -:2:3
  wire done12 = out12_ready & _GEN_11 | emitted_12;	// -:2:3
  reg  emitted_13;	// -:2:3
  wire _GEN_12 = ~emitted_13 & in0_valid;	// -:2:3
  wire done13 = out13_ready & _GEN_12 | emitted_13;	// -:2:3
  reg  emitted_14;	// -:2:3
  wire _GEN_13 = ~emitted_14 & in0_valid;	// -:2:3
  wire done14 = out14_ready & _GEN_13 | emitted_14;	// -:2:3
  reg  emitted_15;	// -:2:3
  wire _GEN_14 = ~emitted_15 & in0_valid;	// -:2:3
  wire done15 = out15_ready & _GEN_14 | emitted_15;	// -:2:3
  reg  emitted_16;	// -:2:3
  wire _GEN_15 = ~emitted_16 & in0_valid;	// -:2:3
  wire done16 = out16_ready & _GEN_15 | emitted_16;	// -:2:3
  reg  emitted_17;	// -:2:3
  wire _GEN_16 = ~emitted_17 & in0_valid;	// -:2:3
  wire done17 = out17_ready & _GEN_16 | emitted_17;	// -:2:3
  reg  emitted_18;	// -:2:3
  wire _GEN_17 = ~emitted_18 & in0_valid;	// -:2:3
  wire done18 = out18_ready & _GEN_17 | emitted_18;	// -:2:3
  reg  emitted_19;	// -:2:3
  wire _GEN_18 = ~emitted_19 & in0_valid;	// -:2:3
  wire done19 = out19_ready & _GEN_18 | emitted_19;	// -:2:3
  reg  emitted_20;	// -:2:3
  wire _GEN_19 = ~emitted_20 & in0_valid;	// -:2:3
  wire done20 = out20_ready & _GEN_19 | emitted_20;	// -:2:3
  reg  emitted_21;	// -:2:3
  wire _GEN_20 = ~emitted_21 & in0_valid;	// -:2:3
  wire done21 = out21_ready & _GEN_20 | emitted_21;	// -:2:3
  reg  emitted_22;	// -:2:3
  wire _GEN_21 = ~emitted_22 & in0_valid;	// -:2:3
  wire done22 = out22_ready & _GEN_21 | emitted_22;	// -:2:3
  reg  emitted_23;	// -:2:3
  wire _GEN_22 = ~emitted_23 & in0_valid;	// -:2:3
  wire done23 = out23_ready & _GEN_22 | emitted_23;	// -:2:3
  reg  emitted_24;	// -:2:3
  wire _GEN_23 = ~emitted_24 & in0_valid;	// -:2:3
  wire done24 = out24_ready & _GEN_23 | emitted_24;	// -:2:3
  reg  emitted_25;	// -:2:3
  wire _GEN_24 = ~emitted_25 & in0_valid;	// -:2:3
  wire done25 = out25_ready & _GEN_24 | emitted_25;	// -:2:3
  reg  emitted_26;	// -:2:3
  wire _GEN_25 = ~emitted_26 & in0_valid;	// -:2:3
  wire done26 = out26_ready & _GEN_25 | emitted_26;	// -:2:3
  reg  emitted_27;	// -:2:3
  wire _GEN_26 = ~emitted_27 & in0_valid;	// -:2:3
  wire done27 = out27_ready & _GEN_26 | emitted_27;	// -:2:3
  reg  emitted_28;	// -:2:3
  wire _GEN_27 = ~emitted_28 & in0_valid;	// -:2:3
  wire done28 = out28_ready & _GEN_27 | emitted_28;	// -:2:3
  reg  emitted_29;	// -:2:3
  wire _GEN_28 = ~emitted_29 & in0_valid;	// -:2:3
  wire done29 = out29_ready & _GEN_28 | emitted_29;	// -:2:3
  reg  emitted_30;	// -:2:3
  wire _GEN_29 = ~emitted_30 & in0_valid;	// -:2:3
  wire done30 = out30_ready & _GEN_29 | emitted_30;	// -:2:3
  reg  emitted_31;	// -:2:3
  wire _GEN_30 = ~emitted_31 & in0_valid;	// -:2:3
  wire done31 = out31_ready & _GEN_30 | emitted_31;	// -:2:3
  reg  emitted_32;	// -:2:3
  wire _GEN_31 = ~emitted_32 & in0_valid;	// -:2:3
  wire done32 = out32_ready & _GEN_31 | emitted_32;	// -:2:3
  reg  emitted_33;	// -:2:3
  wire _GEN_32 = ~emitted_33 & in0_valid;	// -:2:3
  wire done33 = out33_ready & _GEN_32 | emitted_33;	// -:2:3
  reg  emitted_34;	// -:2:3
  wire _GEN_33 = ~emitted_34 & in0_valid;	// -:2:3
  wire done34 = out34_ready & _GEN_33 | emitted_34;	// -:2:3
  reg  emitted_35;	// -:2:3
  wire _GEN_34 = ~emitted_35 & in0_valid;	// -:2:3
  wire done35 = out35_ready & _GEN_34 | emitted_35;	// -:2:3
  reg  emitted_36;	// -:2:3
  wire _GEN_35 = ~emitted_36 & in0_valid;	// -:2:3
  wire done36 = out36_ready & _GEN_35 | emitted_36;	// -:2:3
  reg  emitted_37;	// -:2:3
  wire _GEN_36 = ~emitted_37 & in0_valid;	// -:2:3
  wire done37 = out37_ready & _GEN_36 | emitted_37;	// -:2:3
  reg  emitted_38;	// -:2:3
  wire _GEN_37 = ~emitted_38 & in0_valid;	// -:2:3
  wire done38 = out38_ready & _GEN_37 | emitted_38;	// -:2:3
  reg  emitted_39;	// -:2:3
  wire _GEN_38 = ~emitted_39 & in0_valid;	// -:2:3
  wire done39 = out39_ready & _GEN_38 | emitted_39;	// -:2:3
  reg  emitted_40;	// -:2:3
  wire _GEN_39 = ~emitted_40 & in0_valid;	// -:2:3
  wire done40 = out40_ready & _GEN_39 | emitted_40;	// -:2:3
  reg  emitted_41;	// -:2:3
  wire _GEN_40 = ~emitted_41 & in0_valid;	// -:2:3
  wire done41 = out41_ready & _GEN_40 | emitted_41;	// -:2:3
  reg  emitted_42;	// -:2:3
  wire _GEN_41 = ~emitted_42 & in0_valid;	// -:2:3
  wire done42 = out42_ready & _GEN_41 | emitted_42;	// -:2:3
  reg  emitted_43;	// -:2:3
  wire _GEN_42 = ~emitted_43 & in0_valid;	// -:2:3
  wire done43 = out43_ready & _GEN_42 | emitted_43;	// -:2:3
  reg  emitted_44;	// -:2:3
  wire _GEN_43 = ~emitted_44 & in0_valid;	// -:2:3
  wire done44 = out44_ready & _GEN_43 | emitted_44;	// -:2:3
  reg  emitted_45;	// -:2:3
  wire _GEN_44 = ~emitted_45 & in0_valid;	// -:2:3
  wire done45 = out45_ready & _GEN_44 | emitted_45;	// -:2:3
  reg  emitted_46;	// -:2:3
  wire _GEN_45 = ~emitted_46 & in0_valid;	// -:2:3
  wire done46 = out46_ready & _GEN_45 | emitted_46;	// -:2:3
  reg  emitted_47;	// -:2:3
  wire _GEN_46 = ~emitted_47 & in0_valid;	// -:2:3
  wire done47 = out47_ready & _GEN_46 | emitted_47;	// -:2:3
  reg  emitted_48;	// -:2:3
  wire _GEN_47 = ~emitted_48 & in0_valid;	// -:2:3
  wire done48 = out48_ready & _GEN_47 | emitted_48;	// -:2:3
  reg  emitted_49;	// -:2:3
  wire _GEN_48 = ~emitted_49 & in0_valid;	// -:2:3
  wire done49 = out49_ready & _GEN_48 | emitted_49;	// -:2:3
  reg  emitted_50;	// -:2:3
  wire _GEN_49 = ~emitted_50 & in0_valid;	// -:2:3
  wire done50 = out50_ready & _GEN_49 | emitted_50;	// -:2:3
  reg  emitted_51;	// -:2:3
  wire _GEN_50 = ~emitted_51 & in0_valid;	// -:2:3
  wire done51 = out51_ready & _GEN_50 | emitted_51;	// -:2:3
  reg  emitted_52;	// -:2:3
  wire _GEN_51 = ~emitted_52 & in0_valid;	// -:2:3
  wire done52 = out52_ready & _GEN_51 | emitted_52;	// -:2:3
  reg  emitted_53;	// -:2:3
  wire _GEN_52 = ~emitted_53 & in0_valid;	// -:2:3
  wire done53 = out53_ready & _GEN_52 | emitted_53;	// -:2:3
  reg  emitted_54;	// -:2:3
  wire _GEN_53 = ~emitted_54 & in0_valid;	// -:2:3
  wire done54 = out54_ready & _GEN_53 | emitted_54;	// -:2:3
  reg  emitted_55;	// -:2:3
  wire _GEN_54 = ~emitted_55 & in0_valid;	// -:2:3
  wire done55 = out55_ready & _GEN_54 | emitted_55;	// -:2:3
  reg  emitted_56;	// -:2:3
  wire _GEN_55 = ~emitted_56 & in0_valid;	// -:2:3
  wire done56 = out56_ready & _GEN_55 | emitted_56;	// -:2:3
  reg  emitted_57;	// -:2:3
  wire _GEN_56 = ~emitted_57 & in0_valid;	// -:2:3
  wire done57 = out57_ready & _GEN_56 | emitted_57;	// -:2:3
  reg  emitted_58;	// -:2:3
  wire _GEN_57 = ~emitted_58 & in0_valid;	// -:2:3
  wire done58 = out58_ready & _GEN_57 | emitted_58;	// -:2:3
  reg  emitted_59;	// -:2:3
  wire _GEN_58 = ~emitted_59 & in0_valid;	// -:2:3
  wire done59 = out59_ready & _GEN_58 | emitted_59;	// -:2:3
  reg  emitted_60;	// -:2:3
  wire _GEN_59 = ~emitted_60 & in0_valid;	// -:2:3
  wire done60 = out60_ready & _GEN_59 | emitted_60;	// -:2:3
  reg  emitted_61;	// -:2:3
  wire _GEN_60 = ~emitted_61 & in0_valid;	// -:2:3
  wire done61 = out61_ready & _GEN_60 | emitted_61;	// -:2:3
  reg  emitted_62;	// -:2:3
  wire _GEN_61 = ~emitted_62 & in0_valid;	// -:2:3
  wire done62 = out62_ready & _GEN_61 | emitted_62;	// -:2:3
  reg  emitted_63;	// -:2:3
  wire _GEN_62 = ~emitted_63 & in0_valid;	// -:2:3
  wire done63 = out63_ready & _GEN_62 | emitted_63;	// -:2:3
  reg  emitted_64;	// -:2:3
  wire _GEN_63 = ~emitted_64 & in0_valid;	// -:2:3
  wire done64 = out64_ready & _GEN_63 | emitted_64;	// -:2:3
  reg  emitted_65;	// -:2:3
  wire _GEN_64 = ~emitted_65 & in0_valid;	// -:2:3
  wire done65 = out65_ready & _GEN_64 | emitted_65;	// -:2:3
  reg  emitted_66;	// -:2:3
  wire _GEN_65 = ~emitted_66 & in0_valid;	// -:2:3
  wire done66 = out66_ready & _GEN_65 | emitted_66;	// -:2:3
  reg  emitted_67;	// -:2:3
  wire _GEN_66 = ~emitted_67 & in0_valid;	// -:2:3
  wire done67 = out67_ready & _GEN_66 | emitted_67;	// -:2:3
  reg  emitted_68;	// -:2:3
  wire _GEN_67 = ~emitted_68 & in0_valid;	// -:2:3
  wire done68 = out68_ready & _GEN_67 | emitted_68;	// -:2:3
  reg  emitted_69;	// -:2:3
  wire _GEN_68 = ~emitted_69 & in0_valid;	// -:2:3
  wire done69 = out69_ready & _GEN_68 | emitted_69;	// -:2:3
  reg  emitted_70;	// -:2:3
  wire _GEN_69 = ~emitted_70 & in0_valid;	// -:2:3
  wire done70 = out70_ready & _GEN_69 | emitted_70;	// -:2:3
  reg  emitted_71;	// -:2:3
  wire _GEN_70 = ~emitted_71 & in0_valid;	// -:2:3
  wire done71 = out71_ready & _GEN_70 | emitted_71;	// -:2:3
  reg  emitted_72;	// -:2:3
  wire _GEN_71 = ~emitted_72 & in0_valid;	// -:2:3
  wire done72 = out72_ready & _GEN_71 | emitted_72;	// -:2:3
  reg  emitted_73;	// -:2:3
  wire _GEN_72 = ~emitted_73 & in0_valid;	// -:2:3
  wire done73 = out73_ready & _GEN_72 | emitted_73;	// -:2:3
  reg  emitted_74;	// -:2:3
  wire _GEN_73 = ~emitted_74 & in0_valid;	// -:2:3
  wire done74 = out74_ready & _GEN_73 | emitted_74;	// -:2:3
  reg  emitted_75;	// -:2:3
  wire _GEN_74 = ~emitted_75 & in0_valid;	// -:2:3
  wire done75 = out75_ready & _GEN_74 | emitted_75;	// -:2:3
  reg  emitted_76;	// -:2:3
  wire _GEN_75 = ~emitted_76 & in0_valid;	// -:2:3
  wire done76 = out76_ready & _GEN_75 | emitted_76;	// -:2:3
  reg  emitted_77;	// -:2:3
  wire _GEN_76 = ~emitted_77 & in0_valid;	// -:2:3
  wire done77 = out77_ready & _GEN_76 | emitted_77;	// -:2:3
  reg  emitted_78;	// -:2:3
  wire _GEN_77 = ~emitted_78 & in0_valid;	// -:2:3
  wire done78 = out78_ready & _GEN_77 | emitted_78;	// -:2:3
  reg  emitted_79;	// -:2:3
  wire _GEN_78 = ~emitted_79 & in0_valid;	// -:2:3
  wire done79 = out79_ready & _GEN_78 | emitted_79;	// -:2:3
  reg  emitted_80;	// -:2:3
  wire _GEN_79 = ~emitted_80 & in0_valid;	// -:2:3
  wire done80 = out80_ready & _GEN_79 | emitted_80;	// -:2:3
  reg  emitted_81;	// -:2:3
  wire _GEN_80 = ~emitted_81 & in0_valid;	// -:2:3
  wire done81 = out81_ready & _GEN_80 | emitted_81;	// -:2:3
  reg  emitted_82;	// -:2:3
  wire _GEN_81 = ~emitted_82 & in0_valid;	// -:2:3
  wire done82 = out82_ready & _GEN_81 | emitted_82;	// -:2:3
  reg  emitted_83;	// -:2:3
  wire _GEN_82 = ~emitted_83 & in0_valid;	// -:2:3
  wire done83 = out83_ready & _GEN_82 | emitted_83;	// -:2:3
  reg  emitted_84;	// -:2:3
  wire _GEN_83 = ~emitted_84 & in0_valid;	// -:2:3
  wire done84 = out84_ready & _GEN_83 | emitted_84;	// -:2:3
  reg  emitted_85;	// -:2:3
  always_ff @(posedge clock) begin	// -:2:3
    if (reset) begin	// -:2:3
      emitted_0 <= 1'h0;	// -:2:3
      emitted_1 <= 1'h0;	// -:2:3
      emitted_2 <= 1'h0;	// -:2:3
      emitted_3 <= 1'h0;	// -:2:3
      emitted_4 <= 1'h0;	// -:2:3
      emitted_5 <= 1'h0;	// -:2:3
      emitted_6 <= 1'h0;	// -:2:3
      emitted_7 <= 1'h0;	// -:2:3
      emitted_8 <= 1'h0;	// -:2:3
      emitted_9 <= 1'h0;	// -:2:3
      emitted_10 <= 1'h0;	// -:2:3
      emitted_11 <= 1'h0;	// -:2:3
      emitted_12 <= 1'h0;	// -:2:3
      emitted_13 <= 1'h0;	// -:2:3
      emitted_14 <= 1'h0;	// -:2:3
      emitted_15 <= 1'h0;	// -:2:3
      emitted_16 <= 1'h0;	// -:2:3
      emitted_17 <= 1'h0;	// -:2:3
      emitted_18 <= 1'h0;	// -:2:3
      emitted_19 <= 1'h0;	// -:2:3
      emitted_20 <= 1'h0;	// -:2:3
      emitted_21 <= 1'h0;	// -:2:3
      emitted_22 <= 1'h0;	// -:2:3
      emitted_23 <= 1'h0;	// -:2:3
      emitted_24 <= 1'h0;	// -:2:3
      emitted_25 <= 1'h0;	// -:2:3
      emitted_26 <= 1'h0;	// -:2:3
      emitted_27 <= 1'h0;	// -:2:3
      emitted_28 <= 1'h0;	// -:2:3
      emitted_29 <= 1'h0;	// -:2:3
      emitted_30 <= 1'h0;	// -:2:3
      emitted_31 <= 1'h0;	// -:2:3
      emitted_32 <= 1'h0;	// -:2:3
      emitted_33 <= 1'h0;	// -:2:3
      emitted_34 <= 1'h0;	// -:2:3
      emitted_35 <= 1'h0;	// -:2:3
      emitted_36 <= 1'h0;	// -:2:3
      emitted_37 <= 1'h0;	// -:2:3
      emitted_38 <= 1'h0;	// -:2:3
      emitted_39 <= 1'h0;	// -:2:3
      emitted_40 <= 1'h0;	// -:2:3
      emitted_41 <= 1'h0;	// -:2:3
      emitted_42 <= 1'h0;	// -:2:3
      emitted_43 <= 1'h0;	// -:2:3
      emitted_44 <= 1'h0;	// -:2:3
      emitted_45 <= 1'h0;	// -:2:3
      emitted_46 <= 1'h0;	// -:2:3
      emitted_47 <= 1'h0;	// -:2:3
      emitted_48 <= 1'h0;	// -:2:3
      emitted_49 <= 1'h0;	// -:2:3
      emitted_50 <= 1'h0;	// -:2:3
      emitted_51 <= 1'h0;	// -:2:3
      emitted_52 <= 1'h0;	// -:2:3
      emitted_53 <= 1'h0;	// -:2:3
      emitted_54 <= 1'h0;	// -:2:3
      emitted_55 <= 1'h0;	// -:2:3
      emitted_56 <= 1'h0;	// -:2:3
      emitted_57 <= 1'h0;	// -:2:3
      emitted_58 <= 1'h0;	// -:2:3
      emitted_59 <= 1'h0;	// -:2:3
      emitted_60 <= 1'h0;	// -:2:3
      emitted_61 <= 1'h0;	// -:2:3
      emitted_62 <= 1'h0;	// -:2:3
      emitted_63 <= 1'h0;	// -:2:3
      emitted_64 <= 1'h0;	// -:2:3
      emitted_65 <= 1'h0;	// -:2:3
      emitted_66 <= 1'h0;	// -:2:3
      emitted_67 <= 1'h0;	// -:2:3
      emitted_68 <= 1'h0;	// -:2:3
      emitted_69 <= 1'h0;	// -:2:3
      emitted_70 <= 1'h0;	// -:2:3
      emitted_71 <= 1'h0;	// -:2:3
      emitted_72 <= 1'h0;	// -:2:3
      emitted_73 <= 1'h0;	// -:2:3
      emitted_74 <= 1'h0;	// -:2:3
      emitted_75 <= 1'h0;	// -:2:3
      emitted_76 <= 1'h0;	// -:2:3
      emitted_77 <= 1'h0;	// -:2:3
      emitted_78 <= 1'h0;	// -:2:3
      emitted_79 <= 1'h0;	// -:2:3
      emitted_80 <= 1'h0;	// -:2:3
      emitted_81 <= 1'h0;	// -:2:3
      emitted_82 <= 1'h0;	// -:2:3
      emitted_83 <= 1'h0;	// -:2:3
      emitted_84 <= 1'h0;	// -:2:3
      emitted_85 <= 1'h0;	// -:2:3
    end
    else begin	// -:2:3
      emitted_0 <= done0 & ~allDone;	// -:2:3
      emitted_1 <= done1 & ~allDone;	// -:2:3
      emitted_2 <= done2 & ~allDone;	// -:2:3
      emitted_3 <= done3 & ~allDone;	// -:2:3
      emitted_4 <= done4 & ~allDone;	// -:2:3
      emitted_5 <= done5 & ~allDone;	// -:2:3
      emitted_6 <= done6 & ~allDone;	// -:2:3
      emitted_7 <= done7 & ~allDone;	// -:2:3
      emitted_8 <= done8 & ~allDone;	// -:2:3
      emitted_9 <= done9 & ~allDone;	// -:2:3
      emitted_10 <= done10 & ~allDone;	// -:2:3
      emitted_11 <= done11 & ~allDone;	// -:2:3
      emitted_12 <= done12 & ~allDone;	// -:2:3
      emitted_13 <= done13 & ~allDone;	// -:2:3
      emitted_14 <= done14 & ~allDone;	// -:2:3
      emitted_15 <= done15 & ~allDone;	// -:2:3
      emitted_16 <= done16 & ~allDone;	// -:2:3
      emitted_17 <= done17 & ~allDone;	// -:2:3
      emitted_18 <= done18 & ~allDone;	// -:2:3
      emitted_19 <= done19 & ~allDone;	// -:2:3
      emitted_20 <= done20 & ~allDone;	// -:2:3
      emitted_21 <= done21 & ~allDone;	// -:2:3
      emitted_22 <= done22 & ~allDone;	// -:2:3
      emitted_23 <= done23 & ~allDone;	// -:2:3
      emitted_24 <= done24 & ~allDone;	// -:2:3
      emitted_25 <= done25 & ~allDone;	// -:2:3
      emitted_26 <= done26 & ~allDone;	// -:2:3
      emitted_27 <= done27 & ~allDone;	// -:2:3
      emitted_28 <= done28 & ~allDone;	// -:2:3
      emitted_29 <= done29 & ~allDone;	// -:2:3
      emitted_30 <= done30 & ~allDone;	// -:2:3
      emitted_31 <= done31 & ~allDone;	// -:2:3
      emitted_32 <= done32 & ~allDone;	// -:2:3
      emitted_33 <= done33 & ~allDone;	// -:2:3
      emitted_34 <= done34 & ~allDone;	// -:2:3
      emitted_35 <= done35 & ~allDone;	// -:2:3
      emitted_36 <= done36 & ~allDone;	// -:2:3
      emitted_37 <= done37 & ~allDone;	// -:2:3
      emitted_38 <= done38 & ~allDone;	// -:2:3
      emitted_39 <= done39 & ~allDone;	// -:2:3
      emitted_40 <= done40 & ~allDone;	// -:2:3
      emitted_41 <= done41 & ~allDone;	// -:2:3
      emitted_42 <= done42 & ~allDone;	// -:2:3
      emitted_43 <= done43 & ~allDone;	// -:2:3
      emitted_44 <= done44 & ~allDone;	// -:2:3
      emitted_45 <= done45 & ~allDone;	// -:2:3
      emitted_46 <= done46 & ~allDone;	// -:2:3
      emitted_47 <= done47 & ~allDone;	// -:2:3
      emitted_48 <= done48 & ~allDone;	// -:2:3
      emitted_49 <= done49 & ~allDone;	// -:2:3
      emitted_50 <= done50 & ~allDone;	// -:2:3
      emitted_51 <= done51 & ~allDone;	// -:2:3
      emitted_52 <= done52 & ~allDone;	// -:2:3
      emitted_53 <= done53 & ~allDone;	// -:2:3
      emitted_54 <= done54 & ~allDone;	// -:2:3
      emitted_55 <= done55 & ~allDone;	// -:2:3
      emitted_56 <= done56 & ~allDone;	// -:2:3
      emitted_57 <= done57 & ~allDone;	// -:2:3
      emitted_58 <= done58 & ~allDone;	// -:2:3
      emitted_59 <= done59 & ~allDone;	// -:2:3
      emitted_60 <= done60 & ~allDone;	// -:2:3
      emitted_61 <= done61 & ~allDone;	// -:2:3
      emitted_62 <= done62 & ~allDone;	// -:2:3
      emitted_63 <= done63 & ~allDone;	// -:2:3
      emitted_64 <= done64 & ~allDone;	// -:2:3
      emitted_65 <= done65 & ~allDone;	// -:2:3
      emitted_66 <= done66 & ~allDone;	// -:2:3
      emitted_67 <= done67 & ~allDone;	// -:2:3
      emitted_68 <= done68 & ~allDone;	// -:2:3
      emitted_69 <= done69 & ~allDone;	// -:2:3
      emitted_70 <= done70 & ~allDone;	// -:2:3
      emitted_71 <= done71 & ~allDone;	// -:2:3
      emitted_72 <= done72 & ~allDone;	// -:2:3
      emitted_73 <= done73 & ~allDone;	// -:2:3
      emitted_74 <= done74 & ~allDone;	// -:2:3
      emitted_75 <= done75 & ~allDone;	// -:2:3
      emitted_76 <= done76 & ~allDone;	// -:2:3
      emitted_77 <= done77 & ~allDone;	// -:2:3
      emitted_78 <= done78 & ~allDone;	// -:2:3
      emitted_79 <= done79 & ~allDone;	// -:2:3
      emitted_80 <= done80 & ~allDone;	// -:2:3
      emitted_81 <= done81 & ~allDone;	// -:2:3
      emitted_82 <= done82 & ~allDone;	// -:2:3
      emitted_83 <= done83 & ~allDone;	// -:2:3
      emitted_84 <= done84 & ~allDone;	// -:2:3
      emitted_85 <= done85 & ~allDone;	// -:2:3
    end
  end // always_ff @(posedge)
  wire _GEN_84 = ~emitted_85 & in0_valid;	// -:2:3
  assign done85 = out85_ready & _GEN_84 | emitted_85;	// -:2:3
  assign allDone =
    done0 & done1 & done2 & done3 & done4 & done5 & done6 & done7 & done8 & done9 & done10
    & done11 & done12 & done13 & done14 & done15 & done16 & done17 & done18 & done19
    & done20 & done21 & done22 & done23 & done24 & done25 & done26 & done27 & done28
    & done29 & done30 & done31 & done32 & done33 & done34 & done35 & done36 & done37
    & done38 & done39 & done40 & done41 & done42 & done43 & done44 & done45 & done46
    & done47 & done48 & done49 & done50 & done51 & done52 & done53 & done54 & done55
    & done56 & done57 & done58 & done59 & done60 & done61 & done62 & done63 & done64
    & done65 & done66 & done67 & done68 & done69 & done70 & done71 & done72 & done73
    & done74 & done75 & done76 & done77 & done78 & done79 & done80 & done81 & done82
    & done83 & done84 & done85;	// -:2:3
  assign in0_ready = allDone;	// -:2:3
  // Zero width: assign out0 = in0;	// -:2:3
  assign out0_valid = _GEN;	// -:2:3
  // Zero width: assign out1 = in0;	// -:2:3
  assign out1_valid = _GEN_0;	// -:2:3
  // Zero width: assign out2 = in0;	// -:2:3
  assign out2_valid = _GEN_1;	// -:2:3
  // Zero width: assign out3 = in0;	// -:2:3
  assign out3_valid = _GEN_2;	// -:2:3
  // Zero width: assign out4 = in0;	// -:2:3
  assign out4_valid = _GEN_3;	// -:2:3
  // Zero width: assign out5 = in0;	// -:2:3
  assign out5_valid = _GEN_4;	// -:2:3
  // Zero width: assign out6 = in0;	// -:2:3
  assign out6_valid = _GEN_5;	// -:2:3
  // Zero width: assign out7 = in0;	// -:2:3
  assign out7_valid = _GEN_6;	// -:2:3
  // Zero width: assign out8 = in0;	// -:2:3
  assign out8_valid = _GEN_7;	// -:2:3
  // Zero width: assign out9 = in0;	// -:2:3
  assign out9_valid = _GEN_8;	// -:2:3
  // Zero width: assign out10 = in0;	// -:2:3
  assign out10_valid = _GEN_9;	// -:2:3
  // Zero width: assign out11 = in0;	// -:2:3
  assign out11_valid = _GEN_10;	// -:2:3
  // Zero width: assign out12 = in0;	// -:2:3
  assign out12_valid = _GEN_11;	// -:2:3
  // Zero width: assign out13 = in0;	// -:2:3
  assign out13_valid = _GEN_12;	// -:2:3
  // Zero width: assign out14 = in0;	// -:2:3
  assign out14_valid = _GEN_13;	// -:2:3
  // Zero width: assign out15 = in0;	// -:2:3
  assign out15_valid = _GEN_14;	// -:2:3
  // Zero width: assign out16 = in0;	// -:2:3
  assign out16_valid = _GEN_15;	// -:2:3
  // Zero width: assign out17 = in0;	// -:2:3
  assign out17_valid = _GEN_16;	// -:2:3
  // Zero width: assign out18 = in0;	// -:2:3
  assign out18_valid = _GEN_17;	// -:2:3
  // Zero width: assign out19 = in0;	// -:2:3
  assign out19_valid = _GEN_18;	// -:2:3
  // Zero width: assign out20 = in0;	// -:2:3
  assign out20_valid = _GEN_19;	// -:2:3
  // Zero width: assign out21 = in0;	// -:2:3
  assign out21_valid = _GEN_20;	// -:2:3
  // Zero width: assign out22 = in0;	// -:2:3
  assign out22_valid = _GEN_21;	// -:2:3
  // Zero width: assign out23 = in0;	// -:2:3
  assign out23_valid = _GEN_22;	// -:2:3
  // Zero width: assign out24 = in0;	// -:2:3
  assign out24_valid = _GEN_23;	// -:2:3
  // Zero width: assign out25 = in0;	// -:2:3
  assign out25_valid = _GEN_24;	// -:2:3
  // Zero width: assign out26 = in0;	// -:2:3
  assign out26_valid = _GEN_25;	// -:2:3
  // Zero width: assign out27 = in0;	// -:2:3
  assign out27_valid = _GEN_26;	// -:2:3
  // Zero width: assign out28 = in0;	// -:2:3
  assign out28_valid = _GEN_27;	// -:2:3
  // Zero width: assign out29 = in0;	// -:2:3
  assign out29_valid = _GEN_28;	// -:2:3
  // Zero width: assign out30 = in0;	// -:2:3
  assign out30_valid = _GEN_29;	// -:2:3
  // Zero width: assign out31 = in0;	// -:2:3
  assign out31_valid = _GEN_30;	// -:2:3
  // Zero width: assign out32 = in0;	// -:2:3
  assign out32_valid = _GEN_31;	// -:2:3
  // Zero width: assign out33 = in0;	// -:2:3
  assign out33_valid = _GEN_32;	// -:2:3
  // Zero width: assign out34 = in0;	// -:2:3
  assign out34_valid = _GEN_33;	// -:2:3
  // Zero width: assign out35 = in0;	// -:2:3
  assign out35_valid = _GEN_34;	// -:2:3
  // Zero width: assign out36 = in0;	// -:2:3
  assign out36_valid = _GEN_35;	// -:2:3
  // Zero width: assign out37 = in0;	// -:2:3
  assign out37_valid = _GEN_36;	// -:2:3
  // Zero width: assign out38 = in0;	// -:2:3
  assign out38_valid = _GEN_37;	// -:2:3
  // Zero width: assign out39 = in0;	// -:2:3
  assign out39_valid = _GEN_38;	// -:2:3
  // Zero width: assign out40 = in0;	// -:2:3
  assign out40_valid = _GEN_39;	// -:2:3
  // Zero width: assign out41 = in0;	// -:2:3
  assign out41_valid = _GEN_40;	// -:2:3
  // Zero width: assign out42 = in0;	// -:2:3
  assign out42_valid = _GEN_41;	// -:2:3
  // Zero width: assign out43 = in0;	// -:2:3
  assign out43_valid = _GEN_42;	// -:2:3
  // Zero width: assign out44 = in0;	// -:2:3
  assign out44_valid = _GEN_43;	// -:2:3
  // Zero width: assign out45 = in0;	// -:2:3
  assign out45_valid = _GEN_44;	// -:2:3
  // Zero width: assign out46 = in0;	// -:2:3
  assign out46_valid = _GEN_45;	// -:2:3
  // Zero width: assign out47 = in0;	// -:2:3
  assign out47_valid = _GEN_46;	// -:2:3
  // Zero width: assign out48 = in0;	// -:2:3
  assign out48_valid = _GEN_47;	// -:2:3
  // Zero width: assign out49 = in0;	// -:2:3
  assign out49_valid = _GEN_48;	// -:2:3
  // Zero width: assign out50 = in0;	// -:2:3
  assign out50_valid = _GEN_49;	// -:2:3
  // Zero width: assign out51 = in0;	// -:2:3
  assign out51_valid = _GEN_50;	// -:2:3
  // Zero width: assign out52 = in0;	// -:2:3
  assign out52_valid = _GEN_51;	// -:2:3
  // Zero width: assign out53 = in0;	// -:2:3
  assign out53_valid = _GEN_52;	// -:2:3
  // Zero width: assign out54 = in0;	// -:2:3
  assign out54_valid = _GEN_53;	// -:2:3
  // Zero width: assign out55 = in0;	// -:2:3
  assign out55_valid = _GEN_54;	// -:2:3
  // Zero width: assign out56 = in0;	// -:2:3
  assign out56_valid = _GEN_55;	// -:2:3
  // Zero width: assign out57 = in0;	// -:2:3
  assign out57_valid = _GEN_56;	// -:2:3
  // Zero width: assign out58 = in0;	// -:2:3
  assign out58_valid = _GEN_57;	// -:2:3
  // Zero width: assign out59 = in0;	// -:2:3
  assign out59_valid = _GEN_58;	// -:2:3
  // Zero width: assign out60 = in0;	// -:2:3
  assign out60_valid = _GEN_59;	// -:2:3
  // Zero width: assign out61 = in0;	// -:2:3
  assign out61_valid = _GEN_60;	// -:2:3
  // Zero width: assign out62 = in0;	// -:2:3
  assign out62_valid = _GEN_61;	// -:2:3
  // Zero width: assign out63 = in0;	// -:2:3
  assign out63_valid = _GEN_62;	// -:2:3
  // Zero width: assign out64 = in0;	// -:2:3
  assign out64_valid = _GEN_63;	// -:2:3
  // Zero width: assign out65 = in0;	// -:2:3
  assign out65_valid = _GEN_64;	// -:2:3
  // Zero width: assign out66 = in0;	// -:2:3
  assign out66_valid = _GEN_65;	// -:2:3
  // Zero width: assign out67 = in0;	// -:2:3
  assign out67_valid = _GEN_66;	// -:2:3
  // Zero width: assign out68 = in0;	// -:2:3
  assign out68_valid = _GEN_67;	// -:2:3
  // Zero width: assign out69 = in0;	// -:2:3
  assign out69_valid = _GEN_68;	// -:2:3
  // Zero width: assign out70 = in0;	// -:2:3
  assign out70_valid = _GEN_69;	// -:2:3
  // Zero width: assign out71 = in0;	// -:2:3
  assign out71_valid = _GEN_70;	// -:2:3
  // Zero width: assign out72 = in0;	// -:2:3
  assign out72_valid = _GEN_71;	// -:2:3
  // Zero width: assign out73 = in0;	// -:2:3
  assign out73_valid = _GEN_72;	// -:2:3
  // Zero width: assign out74 = in0;	// -:2:3
  assign out74_valid = _GEN_73;	// -:2:3
  // Zero width: assign out75 = in0;	// -:2:3
  assign out75_valid = _GEN_74;	// -:2:3
  // Zero width: assign out76 = in0;	// -:2:3
  assign out76_valid = _GEN_75;	// -:2:3
  // Zero width: assign out77 = in0;	// -:2:3
  assign out77_valid = _GEN_76;	// -:2:3
  // Zero width: assign out78 = in0;	// -:2:3
  assign out78_valid = _GEN_77;	// -:2:3
  // Zero width: assign out79 = in0;	// -:2:3
  assign out79_valid = _GEN_78;	// -:2:3
  // Zero width: assign out80 = in0;	// -:2:3
  assign out80_valid = _GEN_79;	// -:2:3
  // Zero width: assign out81 = in0;	// -:2:3
  assign out81_valid = _GEN_80;	// -:2:3
  // Zero width: assign out82 = in0;	// -:2:3
  assign out82_valid = _GEN_81;	// -:2:3
  // Zero width: assign out83 = in0;	// -:2:3
  assign out83_valid = _GEN_82;	// -:2:3
  // Zero width: assign out84 = in0;	// -:2:3
  assign out84_valid = _GEN_83;	// -:2:3
  // Zero width: assign out85 = in0;	// -:2:3
  assign out85_valid = _GEN_84;	// -:2:3
endmodule

