// Generated by CIRCT unknown git version
module handshake_constant_c18446744073709551615_out_ui1(
  // input  /*Zero Width*/ ctrl,
     input                 ctrl_valid,
                           out0_ready,
     output                ctrl_ready,
                           out0,
                           out0_valid
);

  assign ctrl_ready = out0_ready;
  assign out0 = 1'h1;
  assign out0_valid = ctrl_valid;
endmodule

