// Generated by CIRCT unknown git version
module handshake_store_in_ui64_ui64_out_ui64_ui64(	// -:19:22
     input  [63:0]         addrIn0,
     input                 addrIn0_valid,
     input  [63:0]         dataIn,
     input                 dataIn_valid,
  // input  /*Zero Width*/ ctrl,
     input                 ctrl_valid,
                           dataToMem_ready,
                           addrOut0_ready,
     output                addrIn0_ready,
                           dataIn_ready,
                           ctrl_ready,
     output [63:0]         dataToMem,
     output                dataToMem_valid,
     output [63:0]         addrOut0,
     output                addrOut0_valid
);

  wire _GEN = dataIn_valid & addrIn0_valid & ctrl_valid;	// -:19:22
  wire _GEN_0 = dataToMem_ready & addrOut0_ready & _GEN;	// -:19:22
  assign addrIn0_ready = _GEN_0;	// -:19:22
  assign dataIn_ready = _GEN_0;	// -:19:22
  assign ctrl_ready = _GEN_0;	// -:19:22
  assign dataToMem = dataIn;	// -:19:22
  assign dataToMem_valid = _GEN;	// -:19:22
  assign addrOut0 = addrIn0;	// -:19:22
  assign addrOut0_valid = _GEN;	// -:19:22
endmodule

