// Generated by CIRCT unknown git version
module handshake_mux_in_ui64_ui1_ui1_out_ui1(	// -:57:11
  input  [63:0] select,
  input         select_valid,
                in0,
                in0_valid,
                in1,
                in1_valid,
                out0_ready,
  output        select_ready,
                in0_ready,
                in1_ready,
                out0,
                out0_valid
);

  wire [1:0] _GEN = 2'h1 << select[0];	// -:57:11
  wire       _GEN_0 = (select[0] ? in1_valid : in0_valid) & select_valid;	// -:57:11
  wire       _GEN_1 = _GEN_0 & out0_ready;	// -:57:11
  assign select_ready = _GEN_1;	// -:57:11
  assign in0_ready = _GEN[0] & _GEN_1;	// -:57:11
  assign in1_ready = _GEN[1] & _GEN_1;	// -:57:11
  assign out0 = select[0] ? in1 : in0;	// -:57:11
  assign out0_valid = _GEN_0;	// -:57:11
endmodule

