// Generated by CIRCT unknown git version
module handshake_join_16ins_1outs_ctrl(	// -:19:22
  // input  /*Zero Width*/ in0,
     input                 in0_valid,
  // input  /*Zero Width*/ in1,
     input                 in1_valid,
  // input  /*Zero Width*/ in2,
     input                 in2_valid,
  // input  /*Zero Width*/ in3,
     input                 in3_valid,
  // input  /*Zero Width*/ in4,
     input                 in4_valid,
  // input  /*Zero Width*/ in5,
     input                 in5_valid,
  // input  /*Zero Width*/ in6,
     input                 in6_valid,
  // input  /*Zero Width*/ in7,
     input                 in7_valid,
  // input  /*Zero Width*/ in8,
     input                 in8_valid,
  // input  /*Zero Width*/ in9,
     input                 in9_valid,
  // input  /*Zero Width*/ in10,
     input                 in10_valid,
  // input  /*Zero Width*/ in11,
     input                 in11_valid,
  // input  /*Zero Width*/ in12,
     input                 in12_valid,
  // input  /*Zero Width*/ in13,
     input                 in13_valid,
  // input  /*Zero Width*/ in14,
     input                 in14_valid,
  // input  /*Zero Width*/ in15,
     input                 in15_valid,
                           out0_ready,
     output                in0_ready,
                           in1_ready,
                           in2_ready,
                           in3_ready,
                           in4_ready,
                           in5_ready,
                           in6_ready,
                           in7_ready,
                           in8_ready,
                           in9_ready,
                           in10_ready,
                           in11_ready,
                           in12_ready,
                           in13_ready,
                           in14_ready,
                           in15_ready,
  // output /*Zero Width*/ out0,
     output                out0_valid
);

  wire _GEN =
    in0_valid & in1_valid & in2_valid & in3_valid & in4_valid & in5_valid & in6_valid
    & in7_valid & in8_valid & in9_valid & in10_valid & in11_valid & in12_valid
    & in13_valid & in14_valid & in15_valid;	// -:19:22
  wire _GEN_0 = out0_ready & _GEN;	// -:19:22
  assign in0_ready = _GEN_0;	// -:19:22
  assign in1_ready = _GEN_0;	// -:19:22
  assign in2_ready = _GEN_0;	// -:19:22
  assign in3_ready = _GEN_0;	// -:19:22
  assign in4_ready = _GEN_0;	// -:19:22
  assign in5_ready = _GEN_0;	// -:19:22
  assign in6_ready = _GEN_0;	// -:19:22
  assign in7_ready = _GEN_0;	// -:19:22
  assign in8_ready = _GEN_0;	// -:19:22
  assign in9_ready = _GEN_0;	// -:19:22
  assign in10_ready = _GEN_0;	// -:19:22
  assign in11_ready = _GEN_0;	// -:19:22
  assign in12_ready = _GEN_0;	// -:19:22
  assign in13_ready = _GEN_0;	// -:19:22
  assign in14_ready = _GEN_0;	// -:19:22
  assign in15_ready = _GEN_0;	// -:19:22
  // Zero width: assign out0 = /*Zero width*/;	// -:19:22
  assign out0_valid = _GEN;	// -:19:22
endmodule

