// Generated by CIRCT unknown git version
module handshake_cond_br_in_ui1_ui64_out_ui64_ui64(	// -:23:5
  input         cond,
                cond_valid,
  input  [63:0] data,
  input         data_valid,
                outTrue_ready,
                outFalse_ready,
  output        cond_ready,
                data_ready,
  output [63:0] outTrue,
  output        outTrue_valid,
  output [63:0] outFalse,
  output        outFalse_valid
);

  wire _GEN = cond_valid & data_valid;	// -:23:5
  wire _GEN_0 = (cond ? outTrue_ready : outFalse_ready) & _GEN;	// -:23:5
  assign cond_ready = _GEN_0;	// -:23:5
  assign data_ready = _GEN_0;	// -:23:5
  assign outTrue = data;	// -:23:5
  assign outTrue_valid = cond & _GEN;	// -:23:5
  assign outFalse = data;	// -:23:5
  assign outFalse_valid = ~cond & _GEN;	// -:23:5
endmodule

