// Generated by CIRCT unknown git version
module handshake_cond_br_in_ui1_2ins_2outs_ctrl(	// -:60:5
     input                 cond,
                           cond_valid,
  // input  /*Zero Width*/ data,
     input                 data_valid,
                           outTrue_ready,
                           outFalse_ready,
     output                cond_ready,
                           data_ready,
  // output /*Zero Width*/ outTrue,
     output                outTrue_valid,
  // output /*Zero Width*/ outFalse,
     output                outFalse_valid
);

  wire _GEN = cond_valid & data_valid;	// -:60:5
  wire _GEN_0 = (cond ? outTrue_ready : outFalse_ready) & _GEN;	// -:60:5
  assign cond_ready = _GEN_0;	// -:60:5
  assign data_ready = _GEN_0;	// -:60:5
  // Zero width: assign outTrue = data;	// -:60:5
  assign outTrue_valid = cond & _GEN;	// -:60:5
  // Zero width: assign outFalse = data;	// -:60:5
  assign outFalse_valid = ~cond & _GEN;	// -:60:5
endmodule

