// Generated by CIRCT unknown git version
module handshake_load_in_ui64_ui64_out_ui64_ui64(	// -:87:18
     input  [63:0]         addrIn0,
     input                 addrIn0_valid,
     input  [63:0]         dataFromMem,
     input                 dataFromMem_valid,
  // input  /*Zero Width*/ ctrl,
     input                 ctrl_valid,
                           dataOut_ready,
                           addrOut0_ready,
     output                addrIn0_ready,
                           dataFromMem_ready,
                           ctrl_ready,
     output [63:0]         dataOut,
     output                dataOut_valid,
     output [63:0]         addrOut0,
     output                addrOut0_valid
);

  wire _GEN = addrIn0_valid & ctrl_valid;	// -:87:18
  wire _GEN_0 = addrOut0_ready & _GEN;	// -:87:18
  assign addrIn0_ready = _GEN_0;	// -:87:18
  assign dataFromMem_ready = dataOut_ready;	// -:87:18
  assign ctrl_ready = _GEN_0;	// -:87:18
  assign dataOut = dataFromMem;	// -:87:18
  assign dataOut_valid = dataFromMem_valid;	// -:87:18
  assign addrOut0 = addrIn0;	// -:87:18
  assign addrOut0_valid = _GEN;	// -:87:18
endmodule

