// Generated by CIRCT unknown git version
module handshake_fork_1ins_3outs_ctrl(
  // input  /*Zero Width*/ in0,
     input                 in0_valid,
                           clock,
                           reset,
                           out0_ready,
                           out1_ready,
                           out2_ready,
     output                in0_ready,
  // output /*Zero Width*/ out0,
     output                out0_valid,
  // output /*Zero Width*/ out1,
     output                out1_valid,
  // output /*Zero Width*/ out2,
     output                out2_valid
);

  wire allDone;
  wire done2;
  reg  emitted_0;
  wire _GEN = ~emitted_0 & in0_valid;
  wire done0 = out0_ready & _GEN | emitted_0;
  reg  emitted_1;
  wire _GEN_0 = ~emitted_1 & in0_valid;
  wire done1 = out1_ready & _GEN_0 | emitted_1;
  reg  emitted_2;
  always_ff @(posedge clock) begin
    if (reset) begin
      emitted_0 <= 1'h0;
      emitted_1 <= 1'h0;
      emitted_2 <= 1'h0;
    end
    else begin
      emitted_0 <= done0 & ~allDone;
      emitted_1 <= done1 & ~allDone;
      emitted_2 <= done2 & ~allDone;
    end
  end // always_ff @(posedge)
  wire _GEN_1 = ~emitted_2 & in0_valid;
  assign done2 = out2_ready & _GEN_1 | emitted_2;
  assign allDone = done0 & done1 & done2;
  assign in0_ready = allDone;
  // Zero width: assign out0 = in0;
  assign out0_valid = _GEN;
  // Zero width: assign out1 = in0;
  assign out1_valid = _GEN_0;
  // Zero width: assign out2 = in0;
  assign out2_valid = _GEN_1;
endmodule

