// Generated by CIRCT unknown git version
module handshake_mux_in_ui64_ui64_ui64_out_ui64(	// -:33:5
  input  [63:0] select,
  input         select_valid,
  input  [63:0] in0,
  input         in0_valid,
  input  [63:0] in1,
  input         in1_valid,
                out0_ready,
  output        select_ready,
                in0_ready,
                in1_ready,
  output [63:0] out0,
  output        out0_valid
);

  wire [1:0] _GEN = 2'h1 << select[0];	// -:33:5
  wire       _GEN_0 = (select[0] ? in1_valid : in0_valid) & select_valid;	// -:33:5
  wire       _GEN_1 = _GEN_0 & out0_ready;	// -:33:5
  assign select_ready = _GEN_1;	// -:33:5
  assign in0_ready = _GEN[0] & _GEN_1;	// -:33:5
  assign in1_ready = _GEN[1] & _GEN_1;	// -:33:5
  assign out0 = select[0] ? in1 : in0;	// -:33:5
  assign out0_valid = _GEN_0;	// -:33:5
endmodule

