// Generated by CIRCT unknown git version
module handshake_constant_c262043836_out_ui64(	// -:5:23
  // input  /*Zero Width*/ ctrl,
     input                 ctrl_valid,
                           out0_ready,
     output                ctrl_ready,
     output [63:0]         out0,
     output                out0_valid
);

  assign ctrl_ready = out0_ready;	// -:5:23
  assign out0 = 64'hF9E78BC;	// -:5:23
  assign out0_valid = ctrl_valid;	// -:5:23
endmodule

