// Generated by CIRCT unknown git version
module handshake_fork_in_ui1_out_ui1_ui1_ui1_ui1_ui1_ui1_ui1_ui1_ui1_ui1(	// -:22:10
  input  in0,
         in0_valid,
         clock,
         reset,
         out0_ready,
         out1_ready,
         out2_ready,
         out3_ready,
         out4_ready,
         out5_ready,
         out6_ready,
         out7_ready,
         out8_ready,
         out9_ready,
  output in0_ready,
         out0,
         out0_valid,
         out1,
         out1_valid,
         out2,
         out2_valid,
         out3,
         out3_valid,
         out4,
         out4_valid,
         out5,
         out5_valid,
         out6,
         out6_valid,
         out7,
         out7_valid,
         out8,
         out8_valid,
         out9,
         out9_valid
);

  wire allDone;	// -:22:10
  wire done9;	// -:22:10
  reg  emitted_0;	// -:22:10
  wire _GEN = ~emitted_0 & in0_valid;	// -:22:10
  wire done0 = out0_ready & _GEN | emitted_0;	// -:22:10
  reg  emitted_1;	// -:22:10
  wire _GEN_0 = ~emitted_1 & in0_valid;	// -:22:10
  wire done1 = out1_ready & _GEN_0 | emitted_1;	// -:22:10
  reg  emitted_2;	// -:22:10
  wire _GEN_1 = ~emitted_2 & in0_valid;	// -:22:10
  wire done2 = out2_ready & _GEN_1 | emitted_2;	// -:22:10
  reg  emitted_3;	// -:22:10
  wire _GEN_2 = ~emitted_3 & in0_valid;	// -:22:10
  wire done3 = out3_ready & _GEN_2 | emitted_3;	// -:22:10
  reg  emitted_4;	// -:22:10
  wire _GEN_3 = ~emitted_4 & in0_valid;	// -:22:10
  wire done4 = out4_ready & _GEN_3 | emitted_4;	// -:22:10
  reg  emitted_5;	// -:22:10
  wire _GEN_4 = ~emitted_5 & in0_valid;	// -:22:10
  wire done5 = out5_ready & _GEN_4 | emitted_5;	// -:22:10
  reg  emitted_6;	// -:22:10
  wire _GEN_5 = ~emitted_6 & in0_valid;	// -:22:10
  wire done6 = out6_ready & _GEN_5 | emitted_6;	// -:22:10
  reg  emitted_7;	// -:22:10
  wire _GEN_6 = ~emitted_7 & in0_valid;	// -:22:10
  wire done7 = out7_ready & _GEN_6 | emitted_7;	// -:22:10
  reg  emitted_8;	// -:22:10
  wire _GEN_7 = ~emitted_8 & in0_valid;	// -:22:10
  wire done8 = out8_ready & _GEN_7 | emitted_8;	// -:22:10
  reg  emitted_9;	// -:22:10
  always_ff @(posedge clock) begin	// -:22:10
    if (reset) begin	// -:22:10
      emitted_0 <= 1'h0;	// -:22:10
      emitted_1 <= 1'h0;	// -:22:10
      emitted_2 <= 1'h0;	// -:22:10
      emitted_3 <= 1'h0;	// -:22:10
      emitted_4 <= 1'h0;	// -:22:10
      emitted_5 <= 1'h0;	// -:22:10
      emitted_6 <= 1'h0;	// -:22:10
      emitted_7 <= 1'h0;	// -:22:10
      emitted_8 <= 1'h0;	// -:22:10
      emitted_9 <= 1'h0;	// -:22:10
    end
    else begin	// -:22:10
      emitted_0 <= done0 & ~allDone;	// -:22:10
      emitted_1 <= done1 & ~allDone;	// -:22:10
      emitted_2 <= done2 & ~allDone;	// -:22:10
      emitted_3 <= done3 & ~allDone;	// -:22:10
      emitted_4 <= done4 & ~allDone;	// -:22:10
      emitted_5 <= done5 & ~allDone;	// -:22:10
      emitted_6 <= done6 & ~allDone;	// -:22:10
      emitted_7 <= done7 & ~allDone;	// -:22:10
      emitted_8 <= done8 & ~allDone;	// -:22:10
      emitted_9 <= done9 & ~allDone;	// -:22:10
    end
  end // always_ff @(posedge)
  wire _GEN_8 = ~emitted_9 & in0_valid;	// -:22:10
  assign done9 = out9_ready & _GEN_8 | emitted_9;	// -:22:10
  assign allDone =
    done0 & done1 & done2 & done3 & done4 & done5 & done6 & done7 & done8 & done9;	// -:22:10
  assign in0_ready = allDone;	// -:22:10
  assign out0 = in0;	// -:22:10
  assign out0_valid = _GEN;	// -:22:10
  assign out1 = in0;	// -:22:10
  assign out1_valid = _GEN_0;	// -:22:10
  assign out2 = in0;	// -:22:10
  assign out2_valid = _GEN_1;	// -:22:10
  assign out3 = in0;	// -:22:10
  assign out3_valid = _GEN_2;	// -:22:10
  assign out4 = in0;	// -:22:10
  assign out4_valid = _GEN_3;	// -:22:10
  assign out5 = in0;	// -:22:10
  assign out5_valid = _GEN_4;	// -:22:10
  assign out6 = in0;	// -:22:10
  assign out6_valid = _GEN_5;	// -:22:10
  assign out7 = in0;	// -:22:10
  assign out7_valid = _GEN_6;	// -:22:10
  assign out8 = in0;	// -:22:10
  assign out8_valid = _GEN_7;	// -:22:10
  assign out9 = in0;	// -:22:10
  assign out9_valid = _GEN_8;	// -:22:10
endmodule

