// Generated by CIRCT unknown git version
module handshake_fork_in_ui64_out_ui64_ui64(	// -:2:45
  input  [63:0] in0,
  input         in0_valid,
                clock,
                reset,
                out0_ready,
                out1_ready,
  output        in0_ready,
  output [63:0] out0,
  output        out0_valid,
  output [63:0] out1,
  output        out1_valid
);

  wire allDone;	// -:2:45
  wire done1;	// -:2:45
  reg  emitted_0;	// -:2:45
  wire _GEN = ~emitted_0 & in0_valid;	// -:2:45
  wire done0 = out0_ready & _GEN | emitted_0;	// -:2:45
  reg  emitted_1;	// -:2:45
  always_ff @(posedge clock) begin	// -:2:45
    if (reset) begin	// -:2:45
      emitted_0 <= 1'h0;	// -:2:45
      emitted_1 <= 1'h0;	// -:2:45
    end
    else begin	// -:2:45
      emitted_0 <= done0 & ~allDone;	// -:2:45
      emitted_1 <= done1 & ~allDone;	// -:2:45
    end
  end // always_ff @(posedge)
  wire _GEN_0 = ~emitted_1 & in0_valid;	// -:2:45
  assign done1 = out1_ready & _GEN_0 | emitted_1;	// -:2:45
  assign allDone = done0 & done1;	// -:2:45
  assign in0_ready = allDone;	// -:2:45
  assign out0 = in0;	// -:2:45
  assign out0_valid = _GEN;	// -:2:45
  assign out1 = in0;	// -:2:45
  assign out1_valid = _GEN_0;	// -:2:45
endmodule

