// Generated by CIRCT unknown git version
module handshake_fork_in_ui1_out_ui1_ui1_ui1_ui1_ui1(	// -:40:10
  input  in0,
         in0_valid,
         clock,
         reset,
         out0_ready,
         out1_ready,
         out2_ready,
         out3_ready,
         out4_ready,
  output in0_ready,
         out0,
         out0_valid,
         out1,
         out1_valid,
         out2,
         out2_valid,
         out3,
         out3_valid,
         out4,
         out4_valid
);

  wire allDone;	// -:40:10
  wire done4;	// -:40:10
  reg  emitted_0;	// -:40:10
  wire _GEN = ~emitted_0 & in0_valid;	// -:40:10
  wire done0 = out0_ready & _GEN | emitted_0;	// -:40:10
  reg  emitted_1;	// -:40:10
  wire _GEN_0 = ~emitted_1 & in0_valid;	// -:40:10
  wire done1 = out1_ready & _GEN_0 | emitted_1;	// -:40:10
  reg  emitted_2;	// -:40:10
  wire _GEN_1 = ~emitted_2 & in0_valid;	// -:40:10
  wire done2 = out2_ready & _GEN_1 | emitted_2;	// -:40:10
  reg  emitted_3;	// -:40:10
  wire _GEN_2 = ~emitted_3 & in0_valid;	// -:40:10
  wire done3 = out3_ready & _GEN_2 | emitted_3;	// -:40:10
  reg  emitted_4;	// -:40:10
  always_ff @(posedge clock) begin	// -:40:10
    if (reset) begin	// -:40:10
      emitted_0 <= 1'h0;	// -:40:10
      emitted_1 <= 1'h0;	// -:40:10
      emitted_2 <= 1'h0;	// -:40:10
      emitted_3 <= 1'h0;	// -:40:10
      emitted_4 <= 1'h0;	// -:40:10
    end
    else begin	// -:40:10
      emitted_0 <= done0 & ~allDone;	// -:40:10
      emitted_1 <= done1 & ~allDone;	// -:40:10
      emitted_2 <= done2 & ~allDone;	// -:40:10
      emitted_3 <= done3 & ~allDone;	// -:40:10
      emitted_4 <= done4 & ~allDone;	// -:40:10
    end
  end // always_ff @(posedge)
  wire _GEN_3 = ~emitted_4 & in0_valid;	// -:40:10
  assign done4 = out4_ready & _GEN_3 | emitted_4;	// -:40:10
  assign allDone = done0 & done1 & done2 & done3 & done4;	// -:40:10
  assign in0_ready = allDone;	// -:40:10
  assign out0 = in0;	// -:40:10
  assign out0_valid = _GEN;	// -:40:10
  assign out1 = in0;	// -:40:10
  assign out1_valid = _GEN_0;	// -:40:10
  assign out2 = in0;	// -:40:10
  assign out2_valid = _GEN_1;	// -:40:10
  assign out3 = in0;	// -:40:10
  assign out3_valid = _GEN_2;	// -:40:10
  assign out4 = in0;	// -:40:10
  assign out4_valid = _GEN_3;	// -:40:10
endmodule

