// Generated by CIRCT unknown git version
module handshake_constant_c4194287_out_ui64(	// -:11:21
  // input  /*Zero Width*/ ctrl,
     input                 ctrl_valid,
                           out0_ready,
     output                ctrl_ready,
     output [63:0]         out0,
     output                out0_valid
);

  assign ctrl_ready = out0_ready;	// -:11:21
  assign out0 = 64'h3FFFEF;	// -:11:21
  assign out0_valid = ctrl_valid;	// -:11:21
endmodule

