// Generated by CIRCT unknown git version
module handshake_fork_in_ui64_out_ui64_ui64_ui64_ui64_ui64_ui64_ui64_ui64_ui64_ui64_ui64_ui64_ui64_ui64_ui64_ui64_ui64_ui64_ui64_ui64_ui64_ui64_ui64_ui64_ui64_ui64_ui64_ui64_ui64_ui64_ui64_ui64_ui64_ui64(
  input  [63:0] in0,
  input         in0_valid,
                clock,
                reset,
                out0_ready,
                out1_ready,
                out2_ready,
                out3_ready,
                out4_ready,
                out5_ready,
                out6_ready,
                out7_ready,
                out8_ready,
                out9_ready,
                out10_ready,
                out11_ready,
                out12_ready,
                out13_ready,
                out14_ready,
                out15_ready,
                out16_ready,
                out17_ready,
                out18_ready,
                out19_ready,
                out20_ready,
                out21_ready,
                out22_ready,
                out23_ready,
                out24_ready,
                out25_ready,
                out26_ready,
                out27_ready,
                out28_ready,
                out29_ready,
                out30_ready,
                out31_ready,
                out32_ready,
                out33_ready,
  output        in0_ready,
  output [63:0] out0,
  output        out0_valid,
  output [63:0] out1,
  output        out1_valid,
  output [63:0] out2,
  output        out2_valid,
  output [63:0] out3,
  output        out3_valid,
  output [63:0] out4,
  output        out4_valid,
  output [63:0] out5,
  output        out5_valid,
  output [63:0] out6,
  output        out6_valid,
  output [63:0] out7,
  output        out7_valid,
  output [63:0] out8,
  output        out8_valid,
  output [63:0] out9,
  output        out9_valid,
  output [63:0] out10,
  output        out10_valid,
  output [63:0] out11,
  output        out11_valid,
  output [63:0] out12,
  output        out12_valid,
  output [63:0] out13,
  output        out13_valid,
  output [63:0] out14,
  output        out14_valid,
  output [63:0] out15,
  output        out15_valid,
  output [63:0] out16,
  output        out16_valid,
  output [63:0] out17,
  output        out17_valid,
  output [63:0] out18,
  output        out18_valid,
  output [63:0] out19,
  output        out19_valid,
  output [63:0] out20,
  output        out20_valid,
  output [63:0] out21,
  output        out21_valid,
  output [63:0] out22,
  output        out22_valid,
  output [63:0] out23,
  output        out23_valid,
  output [63:0] out24,
  output        out24_valid,
  output [63:0] out25,
  output        out25_valid,
  output [63:0] out26,
  output        out26_valid,
  output [63:0] out27,
  output        out27_valid,
  output [63:0] out28,
  output        out28_valid,
  output [63:0] out29,
  output        out29_valid,
  output [63:0] out30,
  output        out30_valid,
  output [63:0] out31,
  output        out31_valid,
  output [63:0] out32,
  output        out32_valid,
  output [63:0] out33,
  output        out33_valid
);

  wire allDone;
  wire done33;
  reg  emitted_0;
  wire _GEN = ~emitted_0 & in0_valid;
  wire done0 = out0_ready & _GEN | emitted_0;
  reg  emitted_1;
  wire _GEN_0 = ~emitted_1 & in0_valid;
  wire done1 = out1_ready & _GEN_0 | emitted_1;
  reg  emitted_2;
  wire _GEN_1 = ~emitted_2 & in0_valid;
  wire done2 = out2_ready & _GEN_1 | emitted_2;
  reg  emitted_3;
  wire _GEN_2 = ~emitted_3 & in0_valid;
  wire done3 = out3_ready & _GEN_2 | emitted_3;
  reg  emitted_4;
  wire _GEN_3 = ~emitted_4 & in0_valid;
  wire done4 = out4_ready & _GEN_3 | emitted_4;
  reg  emitted_5;
  wire _GEN_4 = ~emitted_5 & in0_valid;
  wire done5 = out5_ready & _GEN_4 | emitted_5;
  reg  emitted_6;
  wire _GEN_5 = ~emitted_6 & in0_valid;
  wire done6 = out6_ready & _GEN_5 | emitted_6;
  reg  emitted_7;
  wire _GEN_6 = ~emitted_7 & in0_valid;
  wire done7 = out7_ready & _GEN_6 | emitted_7;
  reg  emitted_8;
  wire _GEN_7 = ~emitted_8 & in0_valid;
  wire done8 = out8_ready & _GEN_7 | emitted_8;
  reg  emitted_9;
  wire _GEN_8 = ~emitted_9 & in0_valid;
  wire done9 = out9_ready & _GEN_8 | emitted_9;
  reg  emitted_10;
  wire _GEN_9 = ~emitted_10 & in0_valid;
  wire done10 = out10_ready & _GEN_9 | emitted_10;
  reg  emitted_11;
  wire _GEN_10 = ~emitted_11 & in0_valid;
  wire done11 = out11_ready & _GEN_10 | emitted_11;
  reg  emitted_12;
  wire _GEN_11 = ~emitted_12 & in0_valid;
  wire done12 = out12_ready & _GEN_11 | emitted_12;
  reg  emitted_13;
  wire _GEN_12 = ~emitted_13 & in0_valid;
  wire done13 = out13_ready & _GEN_12 | emitted_13;
  reg  emitted_14;
  wire _GEN_13 = ~emitted_14 & in0_valid;
  wire done14 = out14_ready & _GEN_13 | emitted_14;
  reg  emitted_15;
  wire _GEN_14 = ~emitted_15 & in0_valid;
  wire done15 = out15_ready & _GEN_14 | emitted_15;
  reg  emitted_16;
  wire _GEN_15 = ~emitted_16 & in0_valid;
  wire done16 = out16_ready & _GEN_15 | emitted_16;
  reg  emitted_17;
  wire _GEN_16 = ~emitted_17 & in0_valid;
  wire done17 = out17_ready & _GEN_16 | emitted_17;
  reg  emitted_18;
  wire _GEN_17 = ~emitted_18 & in0_valid;
  wire done18 = out18_ready & _GEN_17 | emitted_18;
  reg  emitted_19;
  wire _GEN_18 = ~emitted_19 & in0_valid;
  wire done19 = out19_ready & _GEN_18 | emitted_19;
  reg  emitted_20;
  wire _GEN_19 = ~emitted_20 & in0_valid;
  wire done20 = out20_ready & _GEN_19 | emitted_20;
  reg  emitted_21;
  wire _GEN_20 = ~emitted_21 & in0_valid;
  wire done21 = out21_ready & _GEN_20 | emitted_21;
  reg  emitted_22;
  wire _GEN_21 = ~emitted_22 & in0_valid;
  wire done22 = out22_ready & _GEN_21 | emitted_22;
  reg  emitted_23;
  wire _GEN_22 = ~emitted_23 & in0_valid;
  wire done23 = out23_ready & _GEN_22 | emitted_23;
  reg  emitted_24;
  wire _GEN_23 = ~emitted_24 & in0_valid;
  wire done24 = out24_ready & _GEN_23 | emitted_24;
  reg  emitted_25;
  wire _GEN_24 = ~emitted_25 & in0_valid;
  wire done25 = out25_ready & _GEN_24 | emitted_25;
  reg  emitted_26;
  wire _GEN_25 = ~emitted_26 & in0_valid;
  wire done26 = out26_ready & _GEN_25 | emitted_26;
  reg  emitted_27;
  wire _GEN_26 = ~emitted_27 & in0_valid;
  wire done27 = out27_ready & _GEN_26 | emitted_27;
  reg  emitted_28;
  wire _GEN_27 = ~emitted_28 & in0_valid;
  wire done28 = out28_ready & _GEN_27 | emitted_28;
  reg  emitted_29;
  wire _GEN_28 = ~emitted_29 & in0_valid;
  wire done29 = out29_ready & _GEN_28 | emitted_29;
  reg  emitted_30;
  wire _GEN_29 = ~emitted_30 & in0_valid;
  wire done30 = out30_ready & _GEN_29 | emitted_30;
  reg  emitted_31;
  wire _GEN_30 = ~emitted_31 & in0_valid;
  wire done31 = out31_ready & _GEN_30 | emitted_31;
  reg  emitted_32;
  wire _GEN_31 = ~emitted_32 & in0_valid;
  wire done32 = out32_ready & _GEN_31 | emitted_32;
  reg  emitted_33;
  always_ff @(posedge clock) begin
    if (reset) begin
      emitted_0 <= 1'h0;
      emitted_1 <= 1'h0;
      emitted_2 <= 1'h0;
      emitted_3 <= 1'h0;
      emitted_4 <= 1'h0;
      emitted_5 <= 1'h0;
      emitted_6 <= 1'h0;
      emitted_7 <= 1'h0;
      emitted_8 <= 1'h0;
      emitted_9 <= 1'h0;
      emitted_10 <= 1'h0;
      emitted_11 <= 1'h0;
      emitted_12 <= 1'h0;
      emitted_13 <= 1'h0;
      emitted_14 <= 1'h0;
      emitted_15 <= 1'h0;
      emitted_16 <= 1'h0;
      emitted_17 <= 1'h0;
      emitted_18 <= 1'h0;
      emitted_19 <= 1'h0;
      emitted_20 <= 1'h0;
      emitted_21 <= 1'h0;
      emitted_22 <= 1'h0;
      emitted_23 <= 1'h0;
      emitted_24 <= 1'h0;
      emitted_25 <= 1'h0;
      emitted_26 <= 1'h0;
      emitted_27 <= 1'h0;
      emitted_28 <= 1'h0;
      emitted_29 <= 1'h0;
      emitted_30 <= 1'h0;
      emitted_31 <= 1'h0;
      emitted_32 <= 1'h0;
      emitted_33 <= 1'h0;
    end
    else begin
      emitted_0 <= done0 & ~allDone;
      emitted_1 <= done1 & ~allDone;
      emitted_2 <= done2 & ~allDone;
      emitted_3 <= done3 & ~allDone;
      emitted_4 <= done4 & ~allDone;
      emitted_5 <= done5 & ~allDone;
      emitted_6 <= done6 & ~allDone;
      emitted_7 <= done7 & ~allDone;
      emitted_8 <= done8 & ~allDone;
      emitted_9 <= done9 & ~allDone;
      emitted_10 <= done10 & ~allDone;
      emitted_11 <= done11 & ~allDone;
      emitted_12 <= done12 & ~allDone;
      emitted_13 <= done13 & ~allDone;
      emitted_14 <= done14 & ~allDone;
      emitted_15 <= done15 & ~allDone;
      emitted_16 <= done16 & ~allDone;
      emitted_17 <= done17 & ~allDone;
      emitted_18 <= done18 & ~allDone;
      emitted_19 <= done19 & ~allDone;
      emitted_20 <= done20 & ~allDone;
      emitted_21 <= done21 & ~allDone;
      emitted_22 <= done22 & ~allDone;
      emitted_23 <= done23 & ~allDone;
      emitted_24 <= done24 & ~allDone;
      emitted_25 <= done25 & ~allDone;
      emitted_26 <= done26 & ~allDone;
      emitted_27 <= done27 & ~allDone;
      emitted_28 <= done28 & ~allDone;
      emitted_29 <= done29 & ~allDone;
      emitted_30 <= done30 & ~allDone;
      emitted_31 <= done31 & ~allDone;
      emitted_32 <= done32 & ~allDone;
      emitted_33 <= done33 & ~allDone;
    end
  end // always_ff @(posedge)
  wire _GEN_32 = ~emitted_33 & in0_valid;
  assign done33 = out33_ready & _GEN_32 | emitted_33;
  assign allDone =
    done0 & done1 & done2 & done3 & done4 & done5 & done6 & done7 & done8 & done9 & done10
    & done11 & done12 & done13 & done14 & done15 & done16 & done17 & done18 & done19
    & done20 & done21 & done22 & done23 & done24 & done25 & done26 & done27 & done28
    & done29 & done30 & done31 & done32 & done33;
  assign in0_ready = allDone;
  assign out0 = in0;
  assign out0_valid = _GEN;
  assign out1 = in0;
  assign out1_valid = _GEN_0;
  assign out2 = in0;
  assign out2_valid = _GEN_1;
  assign out3 = in0;
  assign out3_valid = _GEN_2;
  assign out4 = in0;
  assign out4_valid = _GEN_3;
  assign out5 = in0;
  assign out5_valid = _GEN_4;
  assign out6 = in0;
  assign out6_valid = _GEN_5;
  assign out7 = in0;
  assign out7_valid = _GEN_6;
  assign out8 = in0;
  assign out8_valid = _GEN_7;
  assign out9 = in0;
  assign out9_valid = _GEN_8;
  assign out10 = in0;
  assign out10_valid = _GEN_9;
  assign out11 = in0;
  assign out11_valid = _GEN_10;
  assign out12 = in0;
  assign out12_valid = _GEN_11;
  assign out13 = in0;
  assign out13_valid = _GEN_12;
  assign out14 = in0;
  assign out14_valid = _GEN_13;
  assign out15 = in0;
  assign out15_valid = _GEN_14;
  assign out16 = in0;
  assign out16_valid = _GEN_15;
  assign out17 = in0;
  assign out17_valid = _GEN_16;
  assign out18 = in0;
  assign out18_valid = _GEN_17;
  assign out19 = in0;
  assign out19_valid = _GEN_18;
  assign out20 = in0;
  assign out20_valid = _GEN_19;
  assign out21 = in0;
  assign out21_valid = _GEN_20;
  assign out22 = in0;
  assign out22_valid = _GEN_21;
  assign out23 = in0;
  assign out23_valid = _GEN_22;
  assign out24 = in0;
  assign out24_valid = _GEN_23;
  assign out25 = in0;
  assign out25_valid = _GEN_24;
  assign out26 = in0;
  assign out26_valid = _GEN_25;
  assign out27 = in0;
  assign out27_valid = _GEN_26;
  assign out28 = in0;
  assign out28_valid = _GEN_27;
  assign out29 = in0;
  assign out29_valid = _GEN_28;
  assign out30 = in0;
  assign out30_valid = _GEN_29;
  assign out31 = in0;
  assign out31_valid = _GEN_30;
  assign out32 = in0;
  assign out32_valid = _GEN_31;
  assign out33 = in0;
  assign out33_valid = _GEN_32;
endmodule

