// Generated by CIRCT unknown git version
module handshake_join_6ins_1outs_ctrl(	// -:19:22
  // input  /*Zero Width*/ in0,
     input                 in0_valid,
  // input  /*Zero Width*/ in1,
     input                 in1_valid,
  // input  /*Zero Width*/ in2,
     input                 in2_valid,
  // input  /*Zero Width*/ in3,
     input                 in3_valid,
  // input  /*Zero Width*/ in4,
     input                 in4_valid,
  // input  /*Zero Width*/ in5,
     input                 in5_valid,
                           out0_ready,
     output                in0_ready,
                           in1_ready,
                           in2_ready,
                           in3_ready,
                           in4_ready,
                           in5_ready,
  // output /*Zero Width*/ out0,
     output                out0_valid
);

  wire _GEN = in0_valid & in1_valid & in2_valid & in3_valid & in4_valid & in5_valid;	// -:19:22
  wire _GEN_0 = out0_ready & _GEN;	// -:19:22
  assign in0_ready = _GEN_0;	// -:19:22
  assign in1_ready = _GEN_0;	// -:19:22
  assign in2_ready = _GEN_0;	// -:19:22
  assign in3_ready = _GEN_0;	// -:19:22
  assign in4_ready = _GEN_0;	// -:19:22
  assign in5_ready = _GEN_0;	// -:19:22
  // Zero width: assign out0 = /*Zero width*/;	// -:19:22
  assign out0_valid = _GEN;	// -:19:22
endmodule

