// Generated by CIRCT unknown git version
module handshake_constant_c131072_out_ui64(	// -:16:20
  // input  /*Zero Width*/ ctrl,
     input                 ctrl_valid,
                           out0_ready,
     output                ctrl_ready,
     output [63:0]         out0,
     output                out0_valid
);

  assign ctrl_ready = out0_ready;	// -:16:20
  assign out0 = 64'h20000;	// -:16:20
  assign out0_valid = ctrl_valid;	// -:16:20
endmodule

