// Generated by CIRCT unknown git version
module handshake_constant_c33543516_out_ui64(	// -:8:22
  // input  /*Zero Width*/ ctrl,
     input                 ctrl_valid,
                           out0_ready,
     output                ctrl_ready,
     output [63:0]         out0,
     output                out0_valid
);

  assign ctrl_ready = out0_ready;	// -:8:22
  assign out0 = 64'h1FFD55C;	// -:8:22
  assign out0_valid = ctrl_valid;	// -:8:22
endmodule

