// Generated by CIRCT unknown git version
module handshake_sink_in_ui64(	// -:23:5
  input  [63:0] in0,
  input         in0_valid,
  output        in0_ready
);

  assign in0_ready = 1'h1;	// -:23:5
endmodule

