// Generated by CIRCT unknown git version
module handshake_fork_in_ui1_out_ui1_ui1(
  input  in0,
         in0_valid,
         clock,
         reset,
         out0_ready,
         out1_ready,
  output in0_ready,
         out0,
         out0_valid,
         out1,
         out1_valid
);

  wire allDone;
  wire done1;
  reg  emitted_0;
  wire _GEN = ~emitted_0 & in0_valid;
  wire done0 = out0_ready & _GEN | emitted_0;
  reg  emitted_1;
  always_ff @(posedge clock) begin
    if (reset) begin
      emitted_0 <= 1'h0;
      emitted_1 <= 1'h0;
    end
    else begin
      emitted_0 <= done0 & ~allDone;
      emitted_1 <= done1 & ~allDone;
    end
  end // always_ff @(posedge)
  wire _GEN_0 = ~emitted_1 & in0_valid;
  assign done1 = out1_ready & _GEN_0 | emitted_1;
  assign allDone = done0 & done1;
  assign in0_ready = allDone;
  assign out0 = in0;
  assign out0_valid = _GEN;
  assign out1 = in0;
  assign out1_valid = _GEN_0;
endmodule

