// Generated by CIRCT unknown git version
module handshake_constant_c32768_out_ui64(	// -:18:19
  // input  /*Zero Width*/ ctrl,
     input                 ctrl_valid,
                           out0_ready,
     output                ctrl_ready,
     output [63:0]         out0,
     output                out0_valid
);

  assign ctrl_ready = out0_ready;	// -:18:19
  assign out0 = 64'h8000;	// -:18:19
  assign out0_valid = ctrl_valid;	// -:18:19
endmodule

