// Generated by CIRCT unknown git version
module handshake_fork_in_ui1_out_ui1_ui1_ui1_ui1_ui1_ui1(	// -:91:11
  input  in0,
         in0_valid,
         clock,
         reset,
         out0_ready,
         out1_ready,
         out2_ready,
         out3_ready,
         out4_ready,
         out5_ready,
  output in0_ready,
         out0,
         out0_valid,
         out1,
         out1_valid,
         out2,
         out2_valid,
         out3,
         out3_valid,
         out4,
         out4_valid,
         out5,
         out5_valid
);

  wire allDone;	// -:91:11
  wire done5;	// -:91:11
  reg  emitted_0;	// -:91:11
  wire _GEN = ~emitted_0 & in0_valid;	// -:91:11
  wire done0 = out0_ready & _GEN | emitted_0;	// -:91:11
  reg  emitted_1;	// -:91:11
  wire _GEN_0 = ~emitted_1 & in0_valid;	// -:91:11
  wire done1 = out1_ready & _GEN_0 | emitted_1;	// -:91:11
  reg  emitted_2;	// -:91:11
  wire _GEN_1 = ~emitted_2 & in0_valid;	// -:91:11
  wire done2 = out2_ready & _GEN_1 | emitted_2;	// -:91:11
  reg  emitted_3;	// -:91:11
  wire _GEN_2 = ~emitted_3 & in0_valid;	// -:91:11
  wire done3 = out3_ready & _GEN_2 | emitted_3;	// -:91:11
  reg  emitted_4;	// -:91:11
  wire _GEN_3 = ~emitted_4 & in0_valid;	// -:91:11
  wire done4 = out4_ready & _GEN_3 | emitted_4;	// -:91:11
  reg  emitted_5;	// -:91:11
  always_ff @(posedge clock) begin	// -:91:11
    if (reset) begin	// -:91:11
      emitted_0 <= 1'h0;	// -:91:11
      emitted_1 <= 1'h0;	// -:91:11
      emitted_2 <= 1'h0;	// -:91:11
      emitted_3 <= 1'h0;	// -:91:11
      emitted_4 <= 1'h0;	// -:91:11
      emitted_5 <= 1'h0;	// -:91:11
    end
    else begin	// -:91:11
      emitted_0 <= done0 & ~allDone;	// -:91:11
      emitted_1 <= done1 & ~allDone;	// -:91:11
      emitted_2 <= done2 & ~allDone;	// -:91:11
      emitted_3 <= done3 & ~allDone;	// -:91:11
      emitted_4 <= done4 & ~allDone;	// -:91:11
      emitted_5 <= done5 & ~allDone;	// -:91:11
    end
  end // always_ff @(posedge)
  wire _GEN_4 = ~emitted_5 & in0_valid;	// -:91:11
  assign done5 = out5_ready & _GEN_4 | emitted_5;	// -:91:11
  assign allDone = done0 & done1 & done2 & done3 & done4 & done5;	// -:91:11
  assign in0_ready = allDone;	// -:91:11
  assign out0 = in0;	// -:91:11
  assign out0_valid = _GEN;	// -:91:11
  assign out1 = in0;	// -:91:11
  assign out1_valid = _GEN_0;	// -:91:11
  assign out2 = in0;	// -:91:11
  assign out2_valid = _GEN_1;	// -:91:11
  assign out3 = in0;	// -:91:11
  assign out3_valid = _GEN_2;	// -:91:11
  assign out4 = in0;	// -:91:11
  assign out4_valid = _GEN_3;	// -:91:11
  assign out5 = in0;	// -:91:11
  assign out5_valid = _GEN_4;	// -:91:11
endmodule

