// Generated by CIRCT unknown git version
module handshake_buffer_in_ui1_out_ui1_2slots_fifo(	// -:21:10
  input  in0,
         in0_valid,
         clock,
         reset,
         out0_ready,
  output in0_ready,
         out0,
         out0_valid
);

  reg  ready1_reg;	// -:21:10
  reg  ready0_reg;	// -:21:10
  reg  valid0_reg;	// -:21:10
  wire _GEN = ~valid0_reg | ~ready0_reg;	// -:21:10
  reg  data0_reg;	// -:21:10
  reg  ctrl_data0_reg;	// -:21:10
  reg  valid1_reg;	// -:21:10
  wire _GEN_0 = ~valid1_reg | ~ready1_reg;	// -:21:10
  reg  data1_reg;	// -:21:10
  reg  ctrl_data1_reg;	// -:21:10
  always_ff @(posedge clock) begin	// -:21:10
    if (reset) begin	// -:21:10
      valid0_reg <= 1'h0;	// -:21:10
      data0_reg <= 1'h0;	// -:21:10
      ready0_reg <= 1'h0;	// -:21:10
      ctrl_data0_reg <= 1'h0;	// -:21:10
      valid1_reg <= 1'h0;	// -:21:10
      data1_reg <= 1'h0;	// -:21:10
      ready1_reg <= 1'h0;	// -:21:10
      ctrl_data1_reg <= 1'h0;	// -:21:10
    end
    else begin	// -:21:10
      automatic logic _GEN_1 = ~_GEN_0 & ~ready0_reg;	// -:21:10
      automatic logic _GEN_2 = _GEN_0 & ready0_reg;	// -:21:10
      automatic logic _GEN_3 = ~out0_ready & ~ready1_reg;	// -:21:10
      automatic logic _GEN_4 = out0_ready & ready1_reg;	// -:21:10
      valid0_reg <= _GEN ? in0_valid : valid0_reg;	// -:21:10
      data0_reg <= _GEN ? in0 : data0_reg;	// -:21:10
      ready0_reg <= ~_GEN_2 & (_GEN_1 ? valid0_reg : ready0_reg);	// -:21:10
      ctrl_data0_reg <= ~_GEN_2 & (_GEN_1 ? data0_reg : ctrl_data0_reg);	// -:21:10
      valid1_reg <= _GEN_0 ? (ready0_reg ? ready0_reg : valid0_reg) : valid1_reg;	// -:21:10
      data1_reg <= _GEN_0 ? (ready0_reg ? ctrl_data0_reg : data0_reg) : data1_reg;	// -:21:10
      ready1_reg <= ~_GEN_4 & (_GEN_3 ? valid1_reg : ready1_reg);	// -:21:10
      ctrl_data1_reg <= ~_GEN_4 & (_GEN_3 ? data1_reg : ctrl_data1_reg);	// -:21:10
    end
  end // always_ff @(posedge)
  assign in0_ready = _GEN;	// -:21:10
  assign out0 = ready1_reg ? ctrl_data1_reg : data1_reg;	// -:21:10
  assign out0_valid = ready1_reg ? ready1_reg : valid1_reg;	// -:21:10
endmodule

