// Generated by CIRCT unknown git version
module handshake_cond_br_in_ui1_ui1_out_ui1_ui1(	// -:41:5
  input  cond,
         cond_valid,
         data,
         data_valid,
         outTrue_ready,
         outFalse_ready,
  output cond_ready,
         data_ready,
         outTrue,
         outTrue_valid,
         outFalse,
         outFalse_valid
);

  wire _GEN = cond_valid & data_valid;	// -:41:5
  wire _GEN_0 = (cond ? outTrue_ready : outFalse_ready) & _GEN;	// -:41:5
  assign cond_ready = _GEN_0;	// -:41:5
  assign data_ready = _GEN_0;	// -:41:5
  assign outTrue = data;	// -:41:5
  assign outTrue_valid = cond & _GEN;	// -:41:5
  assign outFalse = data;	// -:41:5
  assign outFalse_valid = ~cond & _GEN;	// -:41:5
endmodule

